System.setArgument("-debugwin", "no");
function GetUserDefaultLCID() {return 0x411;}
function GetSystemDefaultLCID() {return 0x411;}

function ProductKeyCheck() {
	return [0,1,2,3,0x6E,0x69,0x6E,0x39,8,9,10,11,12];
}
System._readRegValue = System.readRegValue;
System.readRegValue = function(path) {
	var prefix = "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall";
	if(path.substr(0, prefix.length) == prefix) return "1";
	return "";
};
