var all_data = [
[1508074703, "ninetail", "VenusBlood -HYPNO-", "VenusBlood -HYPNO-", ["ninetail/VenusBlood -HYPNO-/patch.tjs"]],
[1506703814, "バグシステム", "ヘイズマン -THE LOCAL HERO-", "ヘイズマン -THE LOCAL HERO-", ["../tools/krz_xp3conv.exe", "バグシステム/ヘイズマン -THE LOCAL HERO-/patch.tjs", "バグシステム/ヘイズマン -THE LOCAL HERO-/xp3filter.tjs"]],
[1501258098, "FrontWing(フロントウイング)", "グリザイア ファントムトリガー", "グリザイア ファントムトリガー Grisia Phantom Trigger Vol.1", ["../tools/krz_xp3conv.exe", "フロントウイング/グリザイア ファントムトリガー/xp3filter.tjs"]],
[1501258098, "FrontWing(フロントウイング)", "グリザイア ファントムトリガー", "グリザイア ファントムトリガー Grisia Phantom Trigger Vol.2", ["../tools/krz_xp3conv.exe", "フロントウイング/グリザイア ファントムトリガー/xp3filter.tjs"]],
[1495805536, "ExTry", "春色吐息－禁録・水蜜桃の姉妹たち－", "春色吐息－禁録・水蜜桃の姉妹たち－", ["../patch/old_core_patch/Override2.tjs", "ExTry/春色吐息－禁録・水蜜桃の姉妹たち－/patch.tjs", "ExTry/春色吐息－禁録・水蜜桃の姉妹たち－/patch2.xp3"]],
[1494267212, "アトリエこぶ", "まいとれい", "まいとれい", ["アトリエこぶ/まいとれい/まいとれい.xp3"]],
[1494039623, "暁WORKS", "ハロー・レディ！", "ハロー・レディ！", ["暁WORKS/ハロー・レディ！/patch.tjs", "暁WORKS/ハロー・レディ！/xp3filter.tjs"]],
[1494039610, "ユニゾンシフト", "おたマ!～おたく仲間はちっこいマニア～", "おたマ!～おたく仲間はちっこいマニア～", ["ユニゾンシフト/おたマ!～おたく仲間はちっこいマニア～/patch.tjs"]],
[1494039601, "りぷる", "ミライセカイのプラネッタ", "ミライセカイのプラネッタ", ["りぷる/ミライセカイのプラネッタ/patch.tjs", "りぷる/ミライセカイのプラネッタ/xp3filter.tjs"]],
[1494039594, "ぱれっと", "晴れときどきお天気雨", "晴れときどきお天気雨", ["ぱれっと/晴れときどきお天気雨/patch.tjs", "ぱれっと/晴れときどきお天気雨/xp3filter.tjs"]],
[1494039590, "ぱれっと", "恋がさくころ桜どき", "恋がさくころ桜どき", ["ぱれっと/恋がさくころ桜どき/patch.tjs", "ぱれっと/恋がさくころ桜どき/xp3filter.tjs"]],
[1494039586, "ぱれっと", "みんな捧げちゃう！", "みんな捧げちゃう！", ["ぱれっと/みんな捧げちゃう！/patch.tjs", "ぱれっと/みんな捧げちゃう！/xp3filter.tjs"]],
[1494039558, "すみっこソフト", "はるまで、くるる。", "はるまで、くるる。", ["すみっこソフト/はるまで、くるる。/patch.tjs"]],
[1494039554, "onomatope", "桜ノーリプライ", "桜ノーリプライ", ["onomatope/桜ノーリプライ/patch.tjs", "onomatope/桜ノーリプライ/xp3filter.tjs"]],
[1494039549, "onomatope", "ずっとすきして たくさんすきして", "ずっとすきして たくさんすきして", ["onomatope/ずっとすきして たくさんすきして/patch.tjs", "onomatope/ずっとすきして たくさんすきして/xp3filter.tjs"]],
[1494039544, "Lass", "少女神域∽少女天獄―The Garden of Fifth Zoa―", "少女神域∽少女天獄―The Garden of Fifth Zoa―", ["Lass/少女神域∽少女天獄―The Garden of Fifth Zoa―/patch.tjs"]],
[1494039539, "feng (フォン)", "ちいさな彼女の小夜曲", "ちいさな彼女の小夜曲", ["feng (フォン)/ちいさな彼女の小夜曲/patch.tjs", "feng (フォン)/ちいさな彼女の小夜曲/xp3filter.tjs"]],
[1494039522, "Etoiles(エトワルズ)", "みずカノ！ ～水着の彼女とHしよっ～", "みずカノ！ ～水着の彼女とHしよっ～", ["Etoiles(エトワルズ)/みずカノ！ ～水着の彼女とHしよっ～/patch.tjs", "Etoiles(エトワルズ)/みずカノ！ ～水着の彼女とHしよっ～/xp3filter.tjs"]],
[1494039518, "bitterdrop", "波間の国のファウスト", "波間の国のファウスト", ["bitterdrop/波間の国のファウスト/patch.tjs"]],
[1494039511, "AXL（アクセル）", "百花繚乱エリクシル ‐Record of Myrtus Revival‐", "百花繚乱エリクシル ‐Record of Myrtus Revival‐", ["AXL（アクセル）/百花繚乱エリクシル ‐Record of Myrtus Revival‐/patch.tjs", "AXL（アクセル）/百花繚乱エリクシル ‐Record of Myrtus Revival‐/xp3filter.tjs"]],
[1494039507, "AXL（アクセル）", "レーシャル・マージ", "レーシャル・マージ", ["AXL（アクセル）/レーシャル・マージ/patch.tjs", "AXL（アクセル）/レーシャル・マージ/xp3filter.tjs"]],
[1494039493, "Alcot", "Clover Day's", "Clover Day's", ["Alcot/Clover Day's/patch.tjs", "Alcot/Clover Day's/xp3filter.tjs"]],
[1493817233, "ぱれっと", "9-nine-ここのつここのかここのいろ", "9-nine-ここのつここのかここのいろ", ["../tools/krz_xp3conv.exe", "ぱれっと/9-nine-ここのつここのかここのいろ/patch.tjs", "ぱれっと/9-nine-ここのつここのかここのいろ/xp3filter.tjs"]],
[1493311552, "娘娘（ニャンニャン）", "JKトラブめいん”s", "JKトラブめいん”s", ["娘娘（ニャンニャン）/JKトラブめいん”s/patch.tjs", "娘娘（ニャンニャン）/JKトラブめいん”s/xp3filter.tjs"]],
[1493311550, "娘娘（ニャンニャン）", "おさこい ～俺と二人の甘々ご奉仕H生活～", "おさこい ～俺と二人の甘々ご奉仕H生活～", ["娘娘（ニャンニャン）/おさこい ～俺と二人の甘々ご奉仕H生活～/patch.tjs", "娘娘（ニャンニャン）/おさこい ～俺と二人の甘々ご奉仕H生活～/xp3filter.tjs"]],
[1493311547, "娘娘（ニャンニャン）", "エロ漫画家さんと貧乏姉妹", "エロ漫画家さんと貧乏姉妹", ["娘娘（ニャンニャン）/エロ漫画家さんと貧乏姉妹/patch.tjs", "娘娘（ニャンニャン）/エロ漫画家さんと貧乏姉妹/xp3filter.tjs"]],
[1493311476, "Lamia", "Trippers. －彼女との学園生活を破壊する、1通の手紙－", "Trippers. －彼女との学園生活を破壊する、1通の手紙－", ["Lamia/Trippers. －彼女との学園生活を破壊する、1通の手紙－/patch.tjs", "Lamia/Trippers. －彼女との学園生活を破壊する、1通の手紙－/patch2.xp3", "Lamia/Trippers. －彼女との学園生活を破壊する、1通の手紙－/xp3filter.tjs"]],
[1493311475, "Lamia", "アイツに調教されるとドMな私は感じちゃう", "アイツに調教されるとドMな私は感じちゃう", ["Lamia/アイツに調教されるとドMな私は感じちゃう/patch.tjs", "Lamia/アイツに調教されるとドMな私は感じちゃう/xp3filter.tjs"]],
[1493311474, "Lamia", "発情スイッチ ～美姉妹が催眠術に堕ちた先～", "発情スイッチ ～美姉妹が催眠術に堕ちた先～", ["Lamia/発情スイッチ ～美姉妹が催眠術に堕ちた先～/patch.tjs", "Lamia/発情スイッチ ～美姉妹が催眠術に堕ちた先～/patch2.xp3", "Lamia/発情スイッチ ～美姉妹が催眠術に堕ちた先～/xp3filter.tjs"]],
[1493310643, "Lamia", "エロ本を捨ててから兄の様子がおかしい", "エロ本を捨ててから兄の様子がおかしい", ["Lamia/エロ本を捨ててから兄の様子がおかしい/patch.tjs", "Lamia/エロ本を捨ててから兄の様子がおかしい/xp3filter.tjs"]],
[1491291740, "AKABEiSOFT3 あかべぇそふとすりぃ", "竜騎士Bloody†Saga", "竜騎士Bloody†Saga", ["AKABEiSOFT3 あかべぇそふとすりぃ/竜騎士Bloody†Saga/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/竜騎士Bloody†Saga/xp3filter.tjs"]],
[1490711154, "SEKAI PROJECT", "Japanese School Life", "Japanese School Life", ["../tools/krz_xp3conv.exe", "SEKAI PROJECT/Japanese School Life/patch.tjs", "SEKAI PROJECT/Japanese School Life/xp3filter.tjs"]],
[1490618901, "AKABEiSOFT3 あかべぇそふとすりぃ", "働くオタクの恋愛事情", "働くオタクの恋愛事情", ["../tools/krz_xp3conv.exe", "AKABEiSOFT3 あかべぇそふとすりぃ/働くオタクの恋愛事情/xp3filter.tjs"]],
[1490616871, "HULOTTE（ユロット）", "神頼みしすぎて俺の未来がヤバい。", "神頼みしすぎて俺の未来がヤバい。", ["HULOTTE（ユロット）/神頼みしすぎて俺の未来がヤバい。/patch.tjs", "HULOTTE（ユロット）/神頼みしすぎて俺の未来がヤバい。/xp3filter.tjs"]],
[1490615206, "hollowings", "hollowings", "赤印", ["hollowings/patch.tjs"]],
[1490615206, "hollowings", "hollowings", "紫罗兰rE", ["hollowings/patch.tjs"]],
[1490615206, "SP-time", "hollowings", "真恋寄语枫秋", ["hollowings/patch.tjs"]],
[1490607707, "Swan スワン", "Swan スワン", "孕ら☆カノ!! ～あの娘とラブラブ孕ぼて性活～", ["Swan スワン/patch.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "The3Days -15人連続レイプ-", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "ナマ配信【来場者数100万を誇るお嬢様との腹ボテＳＥＸ】", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "はじめてどうし２～HAPPYバカップル～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "いつでも性交！？ アイドル学園！", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "もう許してッ！射精管理お姉さん", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "ヤりすぎ！セクハラナース", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "俺の催眠ファンタジア ～エロ催眠で戦女神から魔王までハメ放題！！～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "催眠ファンタジア～聖女から魔王まで、種付け腹ボテやり放題！！～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "犯され勇者～凛々しく世界を救うハズだったボク…～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "犯され勇者Ⅱ～勇者なのに、ちんちんをピクピクされてばかりのボク…～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "犯され勇者III～勇者なのに、ビンカンすぎるボクのおち○ちん…～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "犯され勇者Ⅳ ～もうダメっ。ボクのおち○ちんは限界なのにぃ～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "犯され勇者V～どんなにレベルを上げても、すぐ射精しちゃうボクのおち○ちん…～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "明るく楽しい催眠学園～エロ校則をいっぱい作ったら超リア充になれた！～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "生意気だった、茜ちゃん～47才無職キモデブが飼育して特濃SEXに嵌らせちゃう日記～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "自由自在にエロ催眠～ダメダメの俺でも美少女退魔士と犯りまくり！～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "美少女ＪＫアイドル香澄は 100万人のオ・ナ・ホ(ﾊｰﾄ)", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "ツンデレ従姉妹と小悪魔な姪が可愛すぎるので、エロ教育して孕ませちゃうお話", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "監禁少女【Re birthing】", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "目が覚めたら精液が100倍溜まる身体になってた→大量注入！", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "ディーゼルマイン dieselmine", "ディーゼルマイン", "問答無用!種付け許可証 ～劣等遺伝子の俺でも国家権力でナカ出し放題～", ["ディーゼルマイン/xp3filter.tjs"]],
[1490607524, "すたじおもみじ", "ディーゼルマイン", "高貴なお嬢様を片っ端から孕ませたら、どうなるか？", ["ディーゼルマイン/xp3filter.tjs"]],
[1490463740, "ぱれっとクオリア", "オトメ＊ドメイン（PKG版）", "オトメ＊ドメイン（PKG版）", ["ぱれっとクオリア/オトメ＊ドメイン（PKG版）/patch.tjs", "ぱれっとクオリア/オトメ＊ドメイン（PKG版）/xp3filter.tjs"]],
[1489591549, "Xuse", "聖なるかな 外伝 精霊天翔[STORY ONLY]", "聖なるかな 外伝 精霊天翔[STORY ONLY]", ["Xuse/聖なるかな 外伝 精霊天翔[STORY ONLY]/patch.tjs", "Xuse/聖なるかな 外伝 精霊天翔[STORY ONLY]/xp3filter.tjs"]],
[1489509122, "暁WORKS", "スイセイギンカ", "スイセイギンカ", ["../tools/krz_xp3conv.exe", "暁WORKS/スイセイギンカ/xp3filter.tjs"]],
[1489507539, "C：drive／D：drive", "リア充催眠～リアルが充実する催眠生活はじめました～", "リア充催眠～リアルが充実する催眠生活はじめました～", ["C：drive／D：drive/リア充催眠～リアルが充実する催眠生活はじめました～/patch.tjs", "C：drive／D：drive/リア充催眠～リアルが充実する催眠生活はじめました～/xp3filter.tjs"]],
[1489506983, "ベルゼブブ", "スポットライト☆シンデレラ", "スポットライト☆シンデレラ", ["ベルゼブブ/スポットライト☆シンデレラ/patch.tjs"]],
[1488997786, "リリックボックス", "妹が痔になったので座薬を入れてやった件", "妹が痔になったので座薬を入れてやった件", ["リリックボックス/妹が痔になったので座薬を入れてやった件/data.cf", "リリックボックス/妹が痔になったので座薬を入れてやった件/patch.tjs", "リリックボックス/妹が痔になったので座薬を入れてやった件/patch.xp3"]],
[1488877338, "オレンジペコ", "ヒメと魔神と恋するたましぃ", "ヒメと魔神と恋するたましぃ", ["オレンジペコ/ヒメと魔神と恋するたましぃ/patch.tjs", "オレンジペコ/ヒメと魔神と恋するたましぃ/xp3filter.tjs"]],
[1488869581, "SYOKU", "×× of the Dead", "×× of the Dead", ["SYOKU/×× of the Dead/data.cf", "SYOKU/×× of the Dead/patch.tjs", "SYOKU/×× of the Dead/xp3filter.tjs"]],
[1488814832, "すたじおもみじ", "すたじおもみじ", "びんかん!彼女～オレの清楚な彼女は敏感すぎてすぐにアヘっちゃう!～", ["すたじおもみじ/xp3filter.tjs"]],
[1488814832, "すたじおもみじ", "すたじおもみじ", "危険日ねらって！？孕ませ学園2", ["すたじおもみじ/xp3filter.tjs"]],
[1488814832, "すたじおもみじ", "すたじおもみじ", "危険日狙って！？孕ませ学園", ["すたじおもみじ/xp3filter.tjs"]],
[1488812948, "FrontWing(フロントウイング)", "Corona Blossom", "コロナ・ブロッサム Corona Blossom Vol.1 Gift From the Galaxy", ["../tools/krz_xp3conv.exe", "フロントウイング/Corona Blossom/patch.tjs", "フロントウイング/Corona Blossom/xp3filter.tjs"]],
[1488812948, "FrontWing(フロントウイング)", "Corona Blossom", "コロナ・ブロッサム Corona Blossom Vol.2 The Truth From Beyond", ["../tools/krz_xp3conv.exe", "フロントウイング/Corona Blossom/patch.tjs", "フロントウイング/Corona Blossom/xp3filter.tjs"]],
[1488812948, "FrontWing(フロントウイング)", "Corona Blossom", "コロナ・ブロッサム Corona Blossom Vol.3 Journey to the Stars X-RATED", ["../tools/krz_xp3conv.exe", "フロントウイング/Corona Blossom/patch.tjs", "フロントウイング/Corona Blossom/xp3filter.tjs"]],
[1488793209, "NEKO WORKs", "ネコぱら Vol.2 姉妹ネコのシュクレ", "ネコぱら Vol.2 姉妹ネコのシュクレ", ["NEKO WORKs/ネコぱら Vol.2 姉妹ネコのシュクレ/disable_D3D.zip", "NEKO WORKs/ネコぱら Vol.2 姉妹ネコのシュクレ/krz_xp3conv.exe", "NEKO WORKs/ネコぱら Vol.2 姉妹ネコのシュクレ/patch.tjs", "NEKO WORKs/ネコぱら Vol.2 姉妹ネコのシュクレ/patch.xp3", "NEKO WORKs/ネコぱら Vol.2 姉妹ネコのシュクレ/xp3filter.tjs"]],
[1488793170, "NEKO WORKs", "ネコぱら Vol.1 ソレイユ開店しました！", "ネコぱら Vol.1 ソレイユ開店しました！", ["NEKO WORKs/ネコぱら Vol.1 ソレイユ開店しました！/disable_D3D.zip", "../tools/krz_xp3conv.exe", "NEKO WORKs/ネコぱら Vol.1 ソレイユ開店しました！/patch.tjs", "NEKO WORKs/ネコぱら Vol.1 ソレイユ開店しました！/patch.xp3", "NEKO WORKs/ネコぱら Vol.1 ソレイユ開店しました！/xp3filter.tjs"]],
[1488793123, "NEKO WORKs", "ネコぱら Vol.0", "ネコぱら Vol.0", ["NEKO WORKs/ネコぱら Vol.0/disable_D3D.zip", "../tools/krz_xp3conv.exe", "NEKO WORKs/ネコぱら Vol.0/patch.tjs", "NEKO WORKs/ネコぱら Vol.0/patch.xp3", "NEKO WORKs/ネコぱら Vol.0/xp3filter.tjs"]],
[1488792756, "Monogram", "Monogram", "父娘の秘密～妻に言えない親子の関係～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Monogram", "Monogram", "親娘交流 ～下半身言語でコミュニケーション～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Monogram", "Monogram", "淫妹秘事～姉さんよりも私を孕まさない？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "トルピード", "Monogram", "ヴァージン・ワイフ、密やかな開通～あなた、お父さんに躾けられてしまったの…～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "みるくぱい", "Monogram", "絶頂天使アクメリア", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "TORPEDO", "Monogram", "爆走女装計画 ～もしも俺が女装させられてレディースに入隊させられたら～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "TORPEDO", "Monogram", "淫薬依存学園～もっと…もっとちょうだい！～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "あなたの精液（ミルク）くださいな ～私とボクとどっちがお好み？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "あの夏の不確定な彼女", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ご主人様は、お父さん ～妻には言えないヒミツの遊戯～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ぼくがボクに興奮するわけがないっ！ ～お姉ちゃんの弟女装教育～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "不可視な愛情～透明なボクに感じるママ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "発情淫母～疼く熟体は、その欲情を抑えきれない～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妹蜜　～激ＬＯＶＥ妹はフタナリ妖精～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "湯けむりの背徳交姦 ～幼なじみは、兄嫁で、若女将で、未亡人でした～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "一途に絶対服従な妹をめちゃくちゃにしてみた～愛欲兄妹～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ウチの地味な妹が、こんなに巨乳でエロかったなんて！～濡れたらヌレる発情スイッチ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "セメラレ ～妹で感じるなんて、お兄ちゃんは変態なんだね～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "俺の妹は、ツンデレで変態でした～お兄ちゃんの前でだけなんだからね!", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "兄妹秘哀～イヤなのに、カンじちゃう～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妻のJK妹との学内淫交 ～止められない、背徳への誘惑～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "娘の親友JKとの淫交 ～こんな事が娘や妻にばれたら…～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "義妹のネトリクリニック～妻の知らない入院性活", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "見習い退魔師 本気でイキますっ！", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "愛娘は、マゾ性隷 ～娘だからって遠慮しないでね？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妹ハメ ～あんな奴に渡すくらいなら…！～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妹々こみにゅけ～しょん ～おにいちゃん、大人の遊びシよ？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "軟体レッスン ～いいなり彼女とひみつの放課後～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "淫姉隷属 ～影に潜んだ愛欲と支配～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "幼馴染みが父親とデキていた件について ～おやじからの羞恥ネトリ調教～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "アイドル肉体交感 ～おれがあの子で、あの子がオレ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "アナル＊ティーチャー～感度良肛！？逆レッスン～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "あやまちの密愛～夫に言えない義父との淫交", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "キモオタと言われる俺が、欲求不満な肉穴に中出ししまくりました ～地味だけど実は淫乱な巨乳人妻～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "コスプレ娘M調教 ～お付き合いしてくれるなら、なんでもします……～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ショタチンにアヘる黒ギャル ～マセガキかと思っていたのに…～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "デレツンお姉ちゃんのエッチレッスン ～イジメちゃうのは、愛してるからなんだよ？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ほら、そんなに声を漏らすと彼氏にバレちまうぜ？ ～エロゲ世界でモブの少女を寝取ってみた～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "マジ、もうやめてよっ…！ ～褐色肌に刻まれる家庭狂イクッ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "わ、わたしを縛りたい？ ～僕と地味娘の秘密の関係～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ワタシ、HENTAIになっちゃう ～これが憧れの留学性活！？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "愛娘のお尻はパパ専用 ～妻の前で、こんな事をするなんて…～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "夫に言えない義父との姦淫 ～嫌なのに忘れられなくなりそう～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "黒ギャルビッチに射精管理されました？ ～あーしにいろんな格好させて興奮するとかキモいんですけど～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "母撮 ～堕ちていく母の映像記録", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妻と息子にバレてはいけない背徳の媚熱 ～あやまちの密愛2～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "妖姫エィッチ ～エッチで純情な僕の退魔術～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "隠れて！ドキドキアイドルH！ ～マネージャーとのいけないレッスン？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "姉撮 ～堕ちていくお姉ちゃんを助けられない僕～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "姉巫女の淫欲なる儀式 ～我慢できないぼく～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパタイト", "Monogram", "ふたいもデイズ～おにいちゃん、ナイショでシよ♪～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "すうぃ～と☆SwitcH ～まじわるシセンでとろけるカラダ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "淫艶の湯 ～三代の女将達との密交～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "お兄ちゃん、教えて…… ～義妹とヒミツの保健実習～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "りとる☆ついんず ～すぐにトリコにしてあげる♪～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "お兄ちゃん、教えて…… ～義妹とヒミツの保健実習～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "JuiCy妹☆変態パコりっくす ～目指せ！ モテカワHなオンナノコ♪～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "インモラル・ラヴァーズ ～嫁や義父には言えない家庭の情事～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "お姉ちゃんとショータくんと。 ～ナカを良くするHのカンケイ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "すうぃ～と☆SwitcH ～まじわるシセンでとろけるカラダ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンモライト", "Monogram", "りとる☆ついんず ～すぐにトリコにしてあげる♪～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "スピンドル", "Monogram", "妹乳すきゃんだる ～愛でてよ、お兄ちゃん～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "スピンドル", "Monogram", "みこみこ☆ちぇんじんぐ ～小さいの大きいの、どっちが好き？～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "スピンドル", "Monogram", "痴女志向 ～太ったおじさんじゃなきゃダメなの！～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "スピンドル", "Monogram", "僕と2人のご主人様 ～保険医と同級生の危ない性癖～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "スピンドル", "Monogram", "淫辱痴感 ～あなたなんかには、屈しない！～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "オフパコされたら、エッチなアシスタントができちゃった？～僕が売れっ子になった理由～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "いもうと催眠 ～ナマイキ妹を催眠術で言いなりに！…したつもりが、俺の方がヤられまくってる件について～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "お前の旦那だって俺の妻を奪ったんだから、いいだろう？ ～復讐のネトリ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "お前の妻は、オレの淫乱肉嫁 ～お隣さんは欲求不満でした～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "満淫オーク電車 ～くっ！ 任務じゃなければこんな場所…～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アパダッシュ", "Monogram", "熱闘！ハレンチ運動会！ ～汗だせ、声だせ、精子だせ～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "SPINDLE", "Monogram", "隣妻2 ～夫じゃできないこといっぱいシて～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "アンダームーン", "Monogram", "女学園の性欲食堂 ～特精ソースで傀儡に変わる少女たち～", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "ORCSOFT／DWARFSOFT", "Monogram", "お隣の黒人夫に抱かれて啼き悶える最愛の妻。その引き換えに味わう黒人妻の肌。", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "ORCSOFT／DWARFSOFT", "Monogram", "愛妻日記 特典ＣＤ", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "ORCSOFT／DWARFSOFT", "Monogram", "聖ヤリマンシスターズ　パコパコ日記", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Parthenon（パルテノン）", "Monogram", "弱みを握って人妻とその娘をパコってみた", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Parthenon（パルテノン）", "Monogram", "閃電の守護騎士ニィナ", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Parthenon（パルテノン）", "Monogram", "姉キット-Ｈなお姉ちゃんいりませんか？-", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Parthenon（パルテノン）", "Monogram", "Temptation NAKED", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488792756, "Parthenon（パルテノン）", "Monogram", "Temptation Retaliate", ["Monogram/data.cf", "Monogram/patch.tjs", "Monogram/xp3filter.tjs"]],
[1488716935, "暁WORKS", "コミュ―黒い竜と優しい王国―", "コミュ―黒い竜と優しい王国―", ["暁WORKS/コミュ―黒い竜と優しい王国―/if_files_are_unpacked.zip", "暁WORKS/コミュ―黒い竜と優しい王国―/patch.tjs", "暁WORKS/コミュ―黒い竜と優しい王国―/patch2.xp3", "暁WORKS/コミュ―黒い竜と優しい王国―/xp3filter.tjs"]],
[1488716028, "hibiki works", "LOVELY×CATION", "LOVELY×CATION", ["hibiki works/LOVELY×CATION/patch.tjs", "hibiki works/LOVELY×CATION/xp3filter.tjs"]],
[1488715845, "AKABEiSOFT3 あかべぇそふとすりぃ", "手垢塗れの天使", "手垢塗れの天使", ["AKABEiSOFT3 あかべぇそふとすりぃ/手垢塗れの天使/arc.7z", "AKABEiSOFT3 あかべぇそふとすりぃ/手垢塗れの天使/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/手垢塗れの天使/xp3filter.tjs"]],
[1488714714, "AKABEiSOFT2", "車輪の国、向日葵の少女", "車輪の国、向日葵の少女", ["AKABEiSOFT2/車輪の国、向日葵の少女/patch.tjs"]],
[1488622560, "hibiki works", "LOVELY×CATION2", "LOVELY×CATION2", ["../patch/hibiki works/LOVELY×CATION/xp3filter.tjs", "hibiki works/LOVELY×CATION2/patch.tjs"]],
[1488563710, "Recette", "しゅがてん！-sugarfull tempering-", "しゅがてん！-sugarfull tempering-", ["../tools/krz_xp3conv.exe", "Recette/しゅがてん！-sugarfull tempering-/patch.tjs", "Recette/しゅがてん！-sugarfull tempering-/xp3filter.tjs"]],
[1487862348, "きゃべつそふと", "星恋＊ティンクル", "星恋＊ティンクル", ["きゃべつそふと/星恋＊ティンクル/krz_xp3conv.exe", "きゃべつそふと/星恋＊ティンクル/patch.tjs", "きゃべつそふと/星恋＊ティンクル/xp3filter.tjs"]],
[1486889358, "Lose", "まいてつ", "まいてつ", ["Lose/まいてつ/patch.tjs"]],
[1486744780, "スペルマニアックス", "せきさば!～私立せきがはら学園女子サバイバルゲーム部～", "せきさば!～私立せきがはら学園女子サバイバルゲーム部～", ["スペルマニアックス/せきさば!～私立せきがはら学園女子サバイバルゲーム部～/xp3filter.tjs"]],
[1486662685, "ミルフィーユ", "粘獄のリーゼ", "粘獄のリーゼ", ["ミルフィーユ/粘獄のリーゼ/Override2.tjs"]],
[1486484297, "ソーラレイ", "ハメパコ王様ゲーム～合コン居酒屋編～", "ハメパコ王様ゲーム～合コン居酒屋編～", ["ソーラレイ/ハメパコ王様ゲーム～合コン居酒屋編～/patch.tjs", "ソーラレイ/ハメパコ王様ゲーム～合コン居酒屋編～/xp3filter.tjs"]],
[1486388520, "ミルフィーユ", "極煌戦姫ミストルティア ベルトスクロールアクション", "極煌戦姫ミストルティア ベルトスクロールアクション", ["ミルフィーユ/極煌戦姫ミストルティア ベルトスクロールアクション/patch.tjs"]],
[1485265792, "ゆずソフト", "千恋＊万花", "千恋＊万花", ["ゆずソフト/千恋＊万花/krz_xp3conv.exe", "ゆずソフト/千恋＊万花/patch.tjs", "ゆずソフト/千恋＊万花/xp3filter.tjs"]],
[1484668375, "calmeworld", "KARAKARA", "KARAKARA", ["calmeworld/KARAKARA/krz_xp3conv.exe", "calmeworld/KARAKARA/xp3filter.tjs"]],
[1484667497, "Alcot", "LOVEREC", "LOVEREC", ["../tools/krz_xp3conv.exe"]],
[1484667497, "feng (フォン)", "妹のセイイキ", "妹のセイイキ", ["../tools/krz_xp3conv.exe", "feng (フォン)/妹のセイイキ/patch.tjs", "feng (フォン)/妹のセイイキ/patch2.xp3", "feng (フォン)/妹のセイイキ/xp3filter.tjs"]],
[1484667497, "あっぷりけ", "krz_xp3conv", "花の野に咲くうたかたの", ["../tools/krz_xp3conv.exe"]],
[1484667497, "Black Lilith", "krz_xp3conv", "堕ちる人妻 Animation", ["../tools/krz_xp3conv.exe"]],
[1484667497, "SMILE スミレ", "僕と恋するポンコツアクマ。", "僕と恋するポンコツアクマ。", ["../tools/krz_xp3conv.exe", "SMILE スミレ/僕と恋するポンコツアクマ。/patch.tjs", "SMILE スミレ/僕と恋するポンコツアクマ。/xp3filter.tjs"]],
[1484667497, "SMILE スミレ", "僕と恋するポンコツアクマ。 すっごいえっち！", "僕と恋するポンコツアクマ。 すっごいえっち！", ["../tools/krz_xp3conv.exe", "SMILE スミレ/僕と恋するポンコツアクマ。 すっごいえっち！/patch.tjs", "SMILE スミレ/僕と恋するポンコツアクマ。 すっごいえっち！/xp3filter.tjs"]],
[1484667497, "SWEET＆TEA", "枯れない世界と終わる花", "枯れない世界と終わる花", ["../tools/krz_xp3conv.exe", "SWEET＆TEA/枯れない世界と終わる花/xp3filter.tjs"]],
[1484667497, "あっぷりけ", "時を紡ぐ約束", "時を紡ぐ約束", ["../tools/krz_xp3conv.exe"]],
[1484667497, "まどそふと", "ワガママハイスペック", "ワガママハイスペック", ["../tools/krz_xp3conv.exe", "まどそふと/ワガママハイスペック/xp3filter.tjs"]],
[1483455558, "ARTEMIS(あるてみす)", "xor_hash_addrev", "診断の結果、それは恋の病です", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "Sister Prison", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "Temptation Revenger", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "ふぇら・ふぇちっ！", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "僕と契約して幼なじみ生徒会長に催眠をかけよう！", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "（らぶ）りなアイドル", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "魔孕巫女 ～お清めは愛欲淫靡に～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "妹孕ませっくす", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "♥りの変態日記～痴女になりたい女の子～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "ふぇら・ふぇちっ！～Fella‐Fetish～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "痴漢教師～狙われた牝生徒～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "Parthenon（パルテノン）", "xor_hash_addrev", "家出喫茶～貴方のブースで稼がせて～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "アースガル", "xor_hash_addrev", "らいでぃんぐ いんきゅばす", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "クレージュA(エース)", "xor_hash_addrev", "彼には言えない恥辱の関係～ごめんね、わたし先生のものにされちゃった・・・～", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "ORCSOFT／DWARFSOFT", "xor_hash_addrev", "催眠アイドロップス", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "ORCSOFT／DWARFSOFT", "xor_hash_addrev", "ましゅまろ☆いもうと☆さっきゅばす☆", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1483455558, "ソフトさーくるクレージュ", "xor_hash_addrev", "blue note", ["xor_hash_addrev/patch.tjs", "xor_hash_addrev/xp3filter.tjs"]],
[1482936462, "Lass", "Liber_7 永劫の終わりを待つ君へ", "Liber_7 永劫の終わりを待つ君へ", ["Lass/Liber_7 永劫の終わりを待つ君へ/patch.tjs", "Lass/Liber_7 永劫の終わりを待つ君へ/win32dialog.tjs"]],
[1482602479, "hibiki works", "PURELY×CATION", "PURELY×CATION", ["hibiki works/PURELY×CATION/patch.tjs", "hibiki works/PURELY×CATION/xp3filter.tjs"]],
[1482600678, "hibiki works", "PRETTY×CATION", "PRETTY×CATION", ["hibiki works/PRETTY×CATION/patch.tjs", "hibiki works/PRETTY×CATION/xp3filter.tjs"]],
[1482594754, "AKABEiSOFT3 あかべぇそふとすりぃ", "愚者ノ教鞭 今しかできないことがたくさんあるんだ！", "愚者ノ教鞭 今しかできないことがたくさんあるんだ！", ["AKABEiSOFT3 あかべぇそふとすりぃ/愚者ノ教鞭 今しかできないことがたくさんあるんだ！/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/愚者ノ教鞭 今しかできないことがたくさんあるんだ！/xp3filter.tjs"]],
[1482594224, "AKABEiSOFT3 あかべぇそふとすりぃ", "生命のスペア -I was born for you-", "生命のスペア -I was born for you-", ["AKABEiSOFT3 あかべぇそふとすりぃ/生命のスペア -I was born for you-/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/生命のスペア -I was born for you-/xp3filter.tjs"]],
[1482513115, "STRIPE feat. 戯画", "すぺしゃりて!", "すぺしゃりて!", ["STRIPE feat. 戯画/すぺしゃりて!/patch.tjs", "STRIPE feat. 戯画/すぺしゃりて!/xp3filter.tjs"]],
[1482512783, "STELLAR", "連続＞＞＞レイプ", "連続＞＞＞レイプ", ["STELLAR/連続＞＞＞レイプ/patch.tjs"]],
[1482312819, "NanaWind", "ALIA’s CARNIVAL！", "ALIA’s CARNIVAL！", ["NanaWind/ALIA’s CARNIVAL！/patch.tjs"]],
[1481972159, "AXL（アクセル）", "Dolphin Divers", "Dolphin Divers", ["AXL（アクセル）/Dolphin Divers/patch.tjs", "AXL（アクセル）/Dolphin Divers/xp3filter.tjs"]],
[1481965165, "ALL-TiME", "息子の嫁は親父の女 -女医とナースに仕込む胤-", "息子の嫁は親父の女 -女医とナースに仕込む胤-", ["ALL-TiME/息子の嫁は親父の女 -女医とナースに仕込む胤-/patch2.xp3"]],
[1481947630, "flap", "old", "らぶらぶボイン 妹の巨乳", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "らぶらぶボイン 保健医の巨乳", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "らぶらぶボイン えるしす", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "絶対プリンセスのワンマンバトラー", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "らぶらぶボイン -高飛車の巨乳-", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "母娘妊術くのいちPonPon!!", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "flap", "old", "へんしん彼女～はるかが○○に着替えたら～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "女神凌辱 ～パイズリ姫ベルダンディー～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "女神凌辱 ～肛交僧侶スクルド～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "女神凌辱 ～姦虐戦乙女ブリュンヒルド～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "女神凌辱 ～乱交狩人ウルド～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "痴漢電車Ｆカップ未亡妻れいこ", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "痴漢電車Ｇカップ新妻ちえみ", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "痴漢電車Ｈカップ若妻まいな", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "みるくぱい", "old", "痴漢電車Ｉカップ熟妻きょうこ", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "らぱぷる", "old", "なまたま", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "ローズクラウン", "old", "Bloods～淫落の血族2～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "ローズクラウン", "old", "セーラー服心療妻科 -内緒のえっちなカウンセリング-", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481947630, "黒色槍騎兵", "old", "催淫～生意気な女達の中へサインイン!～", ["../patch/old_core_patch/Override2.tjs", "flap/old/patch.tjs", "flap/old/xp3filter.tjs"]],
[1481126183, "Alcot", "よめがみ My Sweet Goddess!", "よめがみ My Sweet Goddess!", ["Alcot/よめがみ My Sweet Goddess!/krz_xp3conv.exe", "Alcot/よめがみ My Sweet Goddess!/xp3filter.tjs"]],
[1481120404, "GREENWAY", "オナテツ浪漫", "オナテツ浪漫", ["GREENWAY/オナテツ浪漫/patch.tjs"]],
[1480852500, "Alcot", "Clover Day’s Plus", "Clover Day’s Plus", ["Alcot/Clover Day’s Plus/patch.tjs"]],
[1480600282, "ASa Project", "スキとスキとでサンカク恋愛", "スキとスキとでサンカク恋愛", ["ASa Project/スキとスキとでサンカク恋愛/xp3filter.tjs"]],
[1480512224, "Nephrite", "ふれるてラブコネクト ～オレとカノジョの恋愛表現（ラブスキンシップ）～", "ふれるてラブコネクト ～オレとカノジョの恋愛表現（ラブスキンシップ）～", ["Nephrite/ふれるてラブコネクト ～オレとカノジョの恋愛表現（ラブスキンシップ）～/xp3filter.tjs"]],
[1480431626, "Le.Chocolat（ル・ショコラ）", "メイドさんしぃしー", "メイドさんしぃしー", ["Le.Chocolat（ル・ショコラ）/メイドさんしぃしー/Override2.tjs", "Le.Chocolat（ル・ショコラ）/メイドさんしぃしー/patch.tjs"]],
[1480350087, "ぱれっとクオリア", "オトメ＊ドメイン（DL版）", "オトメ＊ドメイン（DL版）", ["ぱれっとクオリア/オトメ＊ドメイン（DL版）/patch.tjs", "ぱれっとクオリア/オトメ＊ドメイン（DL版）/xp3filter.tjs"]],
[1480348477, "EXA", "おあずけフェティッシュ！", "おあずけフェティッシュ！", ["EXA/おあずけフェティッシュ！/xp3filter.tjs"]],
[1480347705, "Curious", "Pink Style", "Pink Style", ["../patch/old_core_patch/Override2.tjs", "Curious/Pink Style/patch.tjs"]],
[1480347705, "PeasSoft", "Pink Style", "永ワ刻－トワコク－", ["../patch/old_core_patch/Override2.tjs", "Curious/Pink Style/patch.tjs"]],
[1480347705, "MEGAMI", "くわいなしょっく！", "くわいなしょっく！", ["../patch/old_core_patch/Override2.tjs", "MEGAMI/くわいなしょっく！/patch.tjs"]],
[1480347705, "TRYSET", "サマー☆すいむっ！ ～私たちどんな恥ずかしい練習にも堪えてみせます～", "サマー☆すいむっ！ ～私たちどんな恥ずかしい練習にも堪えてみせます～", ["../patch/old_core_patch/Override2.tjs", "TRYSET/サマー☆すいむっ！ ～私たちどんな恥ずかしい練習にも堪えてみせます～/patch.tjs"]],
[1480347076, "CLIC CLAC", "田舎でシよう！北海道編 ～ボクと妹たちの夢日記～", "田舎でシよう！北海道編 ～ボクと妹たちの夢日記～", ["CLIC CLAC/田舎でシよう！北海道編 ～ボクと妹たちの夢日記～/patch2.xp3"]],
[1480345954, "chuablesoft", "スイートロビンガール -Sweet Robin Girl-", "スイートロビンガール -Sweet Robin Girl-", ["chuablesoft/スイートロビンガール -Sweet Robin Girl-/AfterInit2.tjs", "chuablesoft/スイートロビンガール -Sweet Robin Girl-/patch.tjs"]],
[1480342874, "スレイブニール", "スレイブニール", "強制AVデビュー 上木愛莉1X歳 ～自慰盗撮から始まった、恥辱と背信の日々～", ["スレイブニール/patch.tjs", "スレイブニール/xp3filter.tjs"]],
[1480342874, "ソーラレイ", "スレイブニール", "オジサン、デートして！～JKギャルとのWINWINデートライフ～", ["スレイブニール/patch.tjs", "スレイブニール/xp3filter.tjs"]],
[1480262372, "ユニゾンシフト・クレア", "ファンタジカル", "ファンタジカル", ["ユニゾンシフト・クレア/ファンタジカル/xp3filter.tjs"]],
[1480258942, "Blue Topaz", "座敷楼 －無垢乙女狂育－", "座敷楼 －無垢乙女狂育－", ["../patch/old_core_patch/Override2.tjs", "Blue Topaz/座敷楼 －無垢乙女狂育－/patch.tjs", "Blue Topaz/座敷楼 －無垢乙女狂育－/xp3filter.tjs"]],
[1480258942, "eclat", "サマーピクチャー～小さな丘の小さな夢～-松本美弥加編-", "サマーピクチャー～小さな丘の小さな夢～-松本美弥加編-", ["../patch/old_core_patch/Override2.tjs", "eclat/サマーピクチャー～小さな丘の小さな夢～-松本美弥加編-/patch.tjs"]],
[1480258942, "FlyingShine黒", "FlyingShine黒", "おまな2 おまえんち萌えてるぞ", ["../patch/old_core_patch/Override2.tjs", "FlyingShine黒/patch.tjs", "FlyingShine黒/xp3filter.tjs"]],
[1480258942, "FlyingShine黒", "FlyingShine黒", "彼女たちの禁忌", ["../patch/old_core_patch/Override2.tjs", "FlyingShine黒/patch.tjs", "FlyingShine黒/xp3filter.tjs"]],
[1480258942, "POISON", "母娘催眠", "母娘催眠", ["POISON/母娘催眠/data.cf", "../patch/old_core_patch/Override2.tjs", "POISON/母娘催眠/patch.tjs", "POISON/母娘催眠/xp3filter.tjs"]],
[1480258942, "Sukaradog（スカラドギ）", "痴態姦賞", "痴態姦賞", ["../patch/old_core_patch/Override2.tjs", "Sukaradog（スカラドギ）/痴態姦賞/patch.tjs", "Sukaradog（スカラドギ）/痴態姦賞/xp3filter.tjs"]],
[1480185000, "戯画", "Blue Destiny", "Blue Destiny", ["戯画/Blue Destiny/patch.tjs"]],
[1480183995, "AXL（アクセル）", "愛しい対象（カノジョ）の護り方", "愛しい対象（カノジョ）の護り方", ["AXL（アクセル）/愛しい対象（カノジョ）の護り方/xp3filter.tjs"]],
[1480183113, "SORAHANE", "さくら、咲きました。", "さくら、咲きました。", ["SORAHANE/さくら、咲きました。/patch.tjs", "SORAHANE/さくら、咲きました。/xp3filter.tjs"]],
[1480182463, "SORAHANE", "AQUA", "AQUA", ["SORAHANE/AQUA/patch.tjs", "SORAHANE/AQUA/xp3filter.tjs"]],
[1480077187, "POISON", "とある家族の寝取られ模様", "とある家族の寝取られ模様", ["POISON/とある家族の寝取られ模様/data.cf", "POISON/とある家族の寝取られ模様/patch.tjs", "POISON/とある家族の寝取られ模様/xp3filter.tjs"]],
[1480077187, "ARTEMIS(あるてみす)", "xor_hash", "姉SUMMER（ねえさま～!）", ["xor_hash/xp3filter.tjs"]],
[1480077187, "ARTEMIS(あるてみす)", "xor_hash", "姉SUMMER！2", ["xor_hash/xp3filter.tjs"]],
[1480077187, "CUBE", "xor_hash", "間宮くんちの五つ子事情", ["xor_hash/xp3filter.tjs"]],
[1480077187, "HULOTTE（ユロット）", "xor_hash", "嫁探しが捗りすぎてヤバい。", ["xor_hash/xp3filter.tjs"]],
[1480077187, "MintCUBE", "xor_hash", "あま恋シロップス ～恥じらう恋心でシたくなる甘神様の恋祭り～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "セイバーフィッシュ", "xor_hash", "Ｗ悪魔のＨなおもてなし　～あなたのミルク私達にちょうだい～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "PULLTOP", "xor_hash", "夏少女", ["xor_hash/xp3filter.tjs"]],
[1480077187, "TECH GIANアーカイブ", "xor_hash", "アマガミ ちょっとおまけ劇場", ["xor_hash/xp3filter.tjs"]],
[1480077187, "ソフトさーくるクレージュ", "xor_hash", "LAND OF THE FREE", ["xor_hash/xp3filter.tjs"]],
[1480077187, "ソフトさーくるクレージュ", "xor_hash", "女子校生放課後性教育～弱みを握って生ハメ性活指導～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "ソフトさーくるクレージュ", "xor_hash", "女子校生脅迫淫行日誌～仲良し巨乳ペット強制絶頂アクメ堕ち～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "クレージュエース", "xor_hash", "姦獄娼女～Slave Girl Breeding～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "クレージュエース", "xor_hash", "妹寝取り～身も心もお兄ちゃんのもの～", ["xor_hash/xp3filter.tjs"]],
[1480077187, "ORC SOFT", "xor_hash", "妻が綺麗になったワケ", ["xor_hash/xp3filter.tjs"]],
[1480076986, "TearDrops", "娼館のエミリー", "娼館のエミリー", ["TearDrops/娼館のエミリー/xp3filter.tjs"]],
[1480076596, "ALL-TiME", "真・蟻地獄", "真・蟻地獄", ["ALL-TiME/真・蟻地獄/patch2.xp3", "ALL-TiME/真・蟻地獄/xp3filter.tjs"]],
[1479742875, "oct works", "なまラブ", "なまラブ", ["oct works/なまラブ/xp3filter.tjs"]],
[1479610923, "10mile", "だめがね", "だめがね", ["10mile/だめがね/xp3filter.tjs"]],
[1470661630, "バグシステム", "死に逝く君、館に芽吹く憎悪", "死に逝く君、館に芽吹く憎悪", ["バグシステム/死に逝く君、館に芽吹く憎悪/xp3filter.tjs"]],
[1466508468, "hibiki works", "PRETTY×CATION2", "PRETTY×CATION2", ["hibiki works/PRETTY×CATION2/patch.tjs", "hibiki works/PRETTY×CATION2/xp3filter.tjs"]],
[1466439920, "セイバーフィッシュ", "ボクだけのライブ ～理性の吹き飛んだアイドルとハメ撮り性交～", "ボクだけのライブ ～理性の吹き飛んだアイドルとハメ撮り性交～", ["セイバーフィッシュ/ボクだけのライブ ～理性の吹き飛んだアイドルとハメ撮り性交～/patch.tjs"]],
[1466439920, "セイバーフィッシュ", "セイバーフィッシュ", "媚薬トランス劣情リリース -可愛いくせに性欲強過ぎの制服女子-", ["セイバーフィッシュ/patch.tjs", "セイバーフィッシュ/xp3filter.tjs"]],
[1466439920, "セイバーフィッシュ", "セイバーフィッシュ", "性感エステ ～淫らな指使いに乱れる女たち～", ["セイバーフィッシュ/patch.tjs", "セイバーフィッシュ/xp3filter.tjs"]],
[1466092003, "AKABEiSOFT3 あかべぇそふとすりぃ", "オモカゲ ～えっちなハプニング！？ なんでもどんとこい！～", "オモカゲ ～えっちなハプニング！？ なんでもどんとこい！～", ["AKABEiSOFT3 あかべぇそふとすりぃ/オモカゲ ～えっちなハプニング！？ なんでもどんとこい！～/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/オモカゲ ～えっちなハプニング！？ なんでもどんとこい！～/xp3filter.tjs"]],
[1465749446, "ONE GAMES", "世界一ヤリたい授業 ～林先生のロリビッチな反転世界～", "世界一ヤリたい授業 ～林先生のロリビッチな反転世界～", ["ONE GAMES/世界一ヤリたい授業 ～林先生のロリビッチな反転世界～/patch.tjs", "ONE GAMES/世界一ヤリたい授業 ～林先生のロリビッチな反転世界～/xp3filter.tjs"]],
[1465745408, "Lass Lunatic", "乱れ雪月華 ～月夜の淫舞、狂気の契り～", "乱れ雪月華 ～月夜の淫舞、狂気の契り～", ["Lass Lunatic/乱れ雪月華 ～月夜の淫舞、狂気の契り～/patch.tjs"]],
[1465745408, "Lass Pixy", "Pure Marriage ～赤い糸物語 まどか編～", "Pure Marriage ～赤い糸物語 まどか編～", ["Lass Pixy/Pure Marriage ～赤い糸物語 まどか編～/patch.tjs"]],
[1465141837, "ORCSOFT／DWARFSOFT", "煌速聖姫パラスアテナ", "煌速聖姫パラスアテナ", ["ORCSOFT／DWARFSOFT/煌速聖姫パラスアテナ/patch.tjs", "ORCSOFT／DWARFSOFT/煌速聖姫パラスアテナ/xp3filter.tjs"]],
[1464709643, "chuablesoft", "恋文ロマンチカ", "恋文ロマンチカ", ["chuablesoft/恋文ロマンチカ/patch.tjs"]],
[1464708175, "スノーフレーク", "狼くんと赤頭巾ちゃん", "狼くんと赤頭巾ちゃん", ["スノーフレーク/狼くんと赤頭巾ちゃん/patch.xp3"]],
[1464706951, "Gloria Works", "虹色旋律", "虹色旋律", ["Gloria Works/虹色旋律/patch.tjs", "Gloria Works/虹色旋律/xp3filter.tjs"]],
[1464544942, "CYCLET", "妖神鎮め 少女の決断、御子の決意", "妖神鎮め 少女の決断、御子の決意", ["CYCLET/妖神鎮め 少女の決断、御子の決意/patch.tjs"]],
[1464544754, "CYCLET", "駄作～アリスとクロエ、結ばれる日～", "駄作～アリスとクロエ、結ばれる日～", ["CYCLET/駄作～アリスとクロエ、結ばれる日～/patch.tjs"]],
[1460474489, "Spicy Tails", "Spicy Tails", "World End Economica Episode 1", ["Spicy Tails/patch.tjs"]],
[1460474489, "Spicy Tails", "Spicy Tails", "World End Economica Episode 2", ["Spicy Tails/patch.tjs"]],
[1458462772, "アメノムラクモ", "アメノムラクモ", "母妹催淫恥育～こんな俺に疼いて悶えろ！", ["アメノムラクモ/Override2.tjs", "アメノムラクモ/patch.tjs", "アメノムラクモ/xp3filter.tjs"]],
[1458462772, "アメノムラクモ", "アメノムラクモ", "堕楽園～美しき新妻 初夜に散る～", ["アメノムラクモ/Override2.tjs", "アメノムラクモ/patch.tjs", "アメノムラクモ/xp3filter.tjs"]],
[1458462772, "アメノムラクモ", "アメノムラクモ", "親友の巨乳ママと中出し性活～こんなに射精してちゃ孕んじゃったね", ["アメノムラクモ/Override2.tjs", "アメノムラクモ/patch.tjs", "アメノムラクモ/xp3filter.tjs"]],
[1457083839, "AXL（アクセル）", "恋する乙女と守護の楯 ～薔薇の聖母～", "恋する乙女と守護の楯 ～薔薇の聖母～", ["AXL（アクセル）/恋する乙女と守護の楯 ～薔薇の聖母～/xp3filter.tjs"]],
[1455894833, "ペペ秘宝館", "淫落のヘルス姫 ～堕ちぶれたりもしたけど、ソニ姫は明るくエッチしちゃいます～", "淫落のヘルス姫 ～堕ちぶれたりもしたけど、ソニ姫は明るくエッチしちゃいます～", ["ペペ秘宝館/淫落のヘルス姫 ～堕ちぶれたりもしたけど、ソニ姫は明るくエッチしちゃいます～/patch.tjs"]],
[1455893040, "SPINDLE", "隣妻2 ～夫じゃできないこといっぱいシて～", "隣妻2 ～夫じゃできないこといっぱいシて～", ["SPINDLE/隣妻2 ～夫じゃできないこといっぱいシて～/data.cf", "SPINDLE/隣妻2 ～夫じゃできないこといっぱいシて～/patch.tjs", "SPINDLE/隣妻2 ～夫じゃできないこといっぱいシて～/xp3filter.tjs"]],
[1455892848, "AKABEiSOFT3 あかべぇそふとすりぃ", "空色イノセント -Sorairo Innocent-", "空色イノセント -Sorairo Innocent-", ["../patch/AKABEiSOFT3 あかべぇそふとすりぃ/できない私が、くり返す。/xp3filter.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/空色イノセント -Sorairo Innocent-/patch.tjs"]],
[1455892416, "AKABEiSOFT3 あかべぇそふとすりぃ", "できない私が、くり返す。", "できない私が、くり返す。", ["AKABEiSOFT3 あかべぇそふとすりぃ/できない私が、くり返す。/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/できない私が、くり返す。/xp3filter.tjs"]],
[1455721026, "AKABEiSOFT3 あかべぇそふとすりぃ", "働くオトナの恋愛事情", "働くオトナの恋愛事情", ["AKABEiSOFT3 あかべぇそふとすりぃ/働くオトナの恋愛事情/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/働くオトナの恋愛事情/xp3filter.tjs"]],
[1454694013, "Lass Lunatic", "乱れ雪月華 ～儚く散る細雪～", "乱れ雪月華 ～儚く散る細雪～", ["Lass Lunatic/乱れ雪月華 ～儚く散る細雪～/patch.tjs"]],
[1454691979, "Eleonora（エレオノーラ）", "大は小を兼ねない", "大は小を兼ねない", ["Eleonora（エレオノーラ）/大は小を兼ねない/data.cf", "Eleonora（エレオノーラ）/大は小を兼ねない/patch.tjs", "Eleonora（エレオノーラ）/大は小を兼ねない/xp3filter.tjs"]],
[1454691979, "Lucha Libre", "催眠交姦", "催眠交姦", ["Lucha Libre/催眠交姦/patch.tjs", "Lucha Libre/催眠交姦/xp3filter.tjs"]],
[1454691293, "Swan スワン", "孕ら巫女姉妹", "孕ら巫女姉妹", ["../patch/old_core_patch/Override2.tjs", "Swan スワン/孕ら巫女姉妹/patch2.xp3"]],
[1454683907, "ALcot ハニカム", "キミのとなりで恋してる！ -THE RESPECTIVE HAPPINESS-", "キミのとなりで恋してる！ -THE RESPECTIVE HAPPINESS-", ["ALcot ハニカム/キミのとなりで恋してる！ -THE RESPECTIVE HAPPINESS-/krz_xp3conv.exe", "ALcot ハニカム/キミのとなりで恋してる！ -THE RESPECTIVE HAPPINESS-/xp3filter.tjs"]],
[1454161946, "あざらしそふと", "ロイヤルガーデン ～乙女に恋する皇子の戯曲～", "ロイヤルガーデン ～乙女に恋する皇子の戯曲～", ["あざらしそふと/ロイヤルガーデン ～乙女に恋する皇子の戯曲～/Override2.tjs", "あざらしそふと/ロイヤルガーデン ～乙女に恋する皇子の戯曲～/patch.tjs", "あざらしそふと/ロイヤルガーデン ～乙女に恋する皇子の戯曲～/xp3filter.tjs"]],
[1454086150, "ABHAR(アーヴァル)", "すまいるCubic!-水平線まで何マイル アフター&アナザーストーリーズ-", "すまいるCubic!-水平線まで何マイル アフター&アナザーストーリーズ-", ["ABHAR(アーヴァル)/すまいるCubic!-水平線まで何マイル アフター&アナザーストーリーズ-/Override2.tjs", "ABHAR(アーヴァル)/すまいるCubic!-水平線まで何マイル アフター&アナザーストーリーズ-/patch_if you want.tjs", "ABHAR(アーヴァル)/すまいるCubic!-水平線まで何マイル アフター&アナザーストーリーズ-/xp3filter.tjs"]],
[1453816443, "ハイクオソフト", "幼なじみとの暮らし方", "幼なじみとの暮らし方", ["ハイクオソフト/幼なじみとの暮らし方/patch.tjs"]],
[1453476161, "ハイクオソフト", "よつのは", "よつのは", ["ハイクオソフト/よつのは/patch.tjs", "ハイクオソフト/よつのは/patch.xp3", "ハイクオソフト/よつのは/xp3filter.tjs"]],
[1453300926, "AKABEiSOFT2", "ぼくの一人戦争", "ぼくの一人戦争", ["AKABEiSOFT2/ぼくの一人戦争/patch.tjs", "AKABEiSOFT2/ぼくの一人戦争/xp3filter.tjs"]],
[1449244210, "AKABEiSOFT3 あかべぇそふとすりぃ", "聖騎士Melty☆Lovers", "聖騎士Melty☆Lovers", ["AKABEiSOFT3 あかべぇそふとすりぃ/聖騎士Melty☆Lovers/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/聖騎士Melty☆Lovers/xp3filter.tjs"]],
[1449147212, "あっぷりけ", "黄昏の先にのぼる明日 -あっぷりけFanDisc-", "黄昏の先にのぼる明日 -あっぷりけFanDisc-", ["あっぷりけ/黄昏の先にのぼる明日 -あっぷりけFanDisc-/patch.tjs", "あっぷりけ/黄昏の先にのぼる明日 -あっぷりけFanDisc-/xp3filter.tjs"]],
[1449145499, "しゃんぐりらすまーと", "恋ではなく", "恋ではなく", ["しゃんぐりらすまーと/恋ではなく/patch.tjs", "しゃんぐりらすまーと/恋ではなく/xp3filter.tjs"]],
[1448992242, "Le.Chocolat（ル・ショコラ）", "ぱ・ぴ・こ・ん～双子の娘はどうきゅうせい～", "ぱ・ぴ・こ・ん～双子の娘はどうきゅうせい～", ["Le.Chocolat（ル・ショコラ）/ぱ・ぴ・こ・ん～双子の娘はどうきゅうせい～/Override2.tjs", "Le.Chocolat（ル・ショコラ）/ぱ・ぴ・こ・ん～双子の娘はどうきゅうせい～/patch.tjs", "Le.Chocolat（ル・ショコラ）/ぱ・ぴ・こ・ん～双子の娘はどうきゅうせい～/xp3filter.tjs"]],
[1448986797, "CroixSoft", "ばれっと☆すたいる", "ばれっと☆すたいる", ["CroixSoft/ばれっと☆すたいる/xp3filter.tjs"]],
[1448985186, "ASa Project", "ひとつ飛ばし恋愛", "ひとつ飛ばし恋愛", ["ASa Project/ひとつ飛ばし恋愛/xp3filter.tjs"]],
[1448897888, "XANADU", "ときどきパクッちゃお", "ときどきパクッちゃお", ["../patch/old_core_patch/Override2.tjs", "XANADU/ときどきパクッちゃお/patch.tjs", "XANADU/ときどきパクッちゃお/xp3filter.tjs"]],
[1448897774, "C：drive／D：drive", "なかだし孕メイド2", "なかだし孕メイド2", ["C：drive／D：drive/なかだし孕メイド2/patch.tjs", "C：drive／D：drive/なかだし孕メイド2/xp3filter.tjs"]],
[1448827764, "ぷちうさ", "キシ×カノ", "キシ×カノ", ["ぷちうさ/キシ×カノ/patch.tjs", "ぷちうさ/キシ×カノ/xp3filter.tjs"]],
[1448813642, "Overflow", "ストリップバトルデイズ", "ストリップバトルデイズ", ["Overflow/ストリップバトルデイズ/patch.tjs"]],
[1448813164, "ORCSOFT／DWARFSOFT", "貞操観念ZERO ～ヤリマン家族とハメ狂い夏休み～", "貞操観念ZERO ～ヤリマン家族とハメ狂い夏休み～", ["ORCSOFT／DWARFSOFT/貞操観念ZERO ～ヤリマン家族とハメ狂い夏休み～/patch.tjs", "ORCSOFT／DWARFSOFT/貞操観念ZERO ～ヤリマン家族とハメ狂い夏休み～/xp3filter.tjs"]],
[1446778343, "縁 -yukari-", "disable_debug", "Junk Seeker", ["disable_debug/patch.tjs"]],
[1446778343, "縁 -yukari-", "disable_debug", "Thief and TROLL", ["disable_debug/patch.tjs"]],
[1446778343, "縁 -yukari-", "disable_debug", "白濁（しろ）の少女", ["disable_debug/patch.tjs"]],
[1446778343, "縁 -yukari-", "disable_debug", "姫巫女・燦", ["disable_debug/patch.tjs"]],
[1446750869, "SLAVEnir", "お願い！もうヤめてッ !! ～爆乳J○は××××の中出し肉便器～", "お願い！もうヤめてッ !! ～爆乳J○は××××の中出し肉便器～", ["SLAVEnir/お願い！もうヤめてッ !! ～爆乳J○は××××の中出し肉便器～/xp3filter.tjs"]],
[1445006355, "ASa Project", "プラマイウォーズ -Puramai Wars-", "プラマイウォーズ -Puramai Wars-", ["ASa Project/プラマイウォーズ -Puramai Wars-/xp3filter.tjs"]],
[1443369096, "POLARSTAR", "僕らの頭上(うえ)に星空(そら)は廻る", "僕らの頭上(うえ)に星空(そら)は廻る", ["POLARSTAR/僕らの頭上(うえ)に星空(そら)は廻る/xp3filter.tjs"]],
[1443282772, "まどそふと", "ヤキモチストリーム", "ヤキモチストリーム", ["まどそふと/ヤキモチストリーム/patch.tjs", "まどそふと/ヤキモチストリーム/xp3filter.tjs"]],
[1443282771, "pure more", "契約彼女 ～新米彼女と始める、とってもHでPureな恋愛レッスン～", "契約彼女 ～新米彼女と始める、とってもHでPureな恋愛レッスン～", ["pure more/契約彼女 ～新米彼女と始める、とってもHでPureな恋愛レッスン～/patch.tjs"]],
[1443282771, "リリックボックス", "ブラコン!なずさおねーちゃんの性活保護", "ブラコン!なずさおねーちゃんの性活保護", ["リリックボックス/ブラコン!なずさおねーちゃんの性活保護/patch.tjs"]],
[1443278247, "ゆずソフト", "サノバウィッチ", "サノバウィッチ", ["ゆずソフト/サノバウィッチ/patch.tjs", "ゆずソフト/サノバウィッチ/patch2.xp3", "ゆずソフト/サノバウィッチ/xp3filter.tjs"]],
[1443115816, "バグシステム", "スクイの小夜曲", "スクイの小夜曲", ["バグシステム/スクイの小夜曲/patch2.xp3", "バグシステム/スクイの小夜曲/xp3filter.tjs"]],
[1443113178, "オレンジエール", "さくらにかげつ", "さくらにかげつ", ["オレンジエール/さくらにかげつ/xp3filter.tjs"]],
[1442124676, "夜兔", "尘沙惑", "尘沙惑", ["夜兔/尘沙惑/patch.tjs", "夜兔/尘沙惑/xp3filter.tjs"]],
[1441885795, "ハイクオソフト", "ひとなつの", "ひとなつの", ["ハイクオソフト/ひとなつの/patch.tjs"]],
[1441861666, "Navel", "Tick! Tack!", "Tick! Tack!", ["Navel/Tick! Tack!/xp3filter.tjs"]],
[1441725607, "KAI", "PENDULUM", "PENDULUM", ["KAI/PENDULUM/xp3filter.tjs"]],
[1441724413, "KAI", "リヴォルバーガール☆ハンマーレディ", "リヴォルバーガール☆ハンマーレディ", ["KAI/リヴォルバーガール☆ハンマーレディ/xp3filter.tjs"]],
[1441723744, "FAIRYTALE フェアリーテール", "ドラゴンズレイド2 催眠魔法と巨乳娘", "ドラゴンズレイド2 催眠魔法と巨乳娘", ["FAIRYTALE フェアリーテール/ドラゴンズレイド2 催眠魔法と巨乳娘/patch.tjs"]],
[1441531605, "Alcot", "サツコイ ～悠久なる恋の歌～", "サツコイ ～悠久なる恋の歌～", ["Alcot/サツコイ ～悠久なる恋の歌～/xp3filter.tjs"]],
[1441531605, "ALcot ハニカム", "キミのとなりで恋してる！", "キミのとなりで恋してる！", ["../patch/Alcot/サツコイ ～悠久なる恋の歌～/xp3filter.tjs"]],
[1441518880, "ALL-TiME", "肉体操作", "肉体操作", ["ALL-TiME/肉体操作/patch.tjs"]],
[1441123936, "NanaWind", "ALIA’s CARNIVAL！ Flowering Sky", "ALIA’s CARNIVAL！ Flowering Sky", ["NanaWind/ALIA’s CARNIVAL！ Flowering Sky/patch.tjs"]],
[1441121901, "Lass", "迷える２人とセカイのすべて LOVE HEAVEN 300％", "迷える２人とセカイのすべて LOVE HEAVEN 300％", ["Lass/迷える２人とセカイのすべて LOVE HEAVEN 300％/patch.tjs"]],
[1441115021, "KAI", "WALPURGIS -ヴァルプルギス-", "WALPURGIS -ヴァルプルギス-", ["KAI/WALPURGIS -ヴァルプルギス-/xp3filter.tjs"]],
[1431006557, "Lass", "迷える２人とセカイのすべて", "迷える２人とセカイのすべて", ["Lass/迷える２人とセカイのすべて/patch.tjs"]],
[1430936733, "Grand Cru", "はっぴぃふぁくとりー", "はっぴぃふぁくとりー", ["Grand Cru/はっぴぃふぁくとりー/patch.tjs"]],
[1430936733, "Grand Cru", "ヌキどきッ!～天使と悪魔の搾精バトル～", "ヌキどきッ!～天使と悪魔の搾精バトル～", ["Grand Cru/ヌキどきッ!～天使と悪魔の搾精バトル～/patch.tjs"]],
[1430753284, "ベルゼブブ", "痴漢の極み", "痴漢の極み", ["ベルゼブブ/痴漢の極み/patch.tjs"]],
[1430047370, "アースガル", "らいでぃんぐ いんきゅばす", "らいでぃんぐ いんきゅばす", ["アースガル/らいでぃんぐ いんきゅばす/xp3filter.tjs"]],
[1430041476, "Terios", "春色☆こみゅにけ～しょん", "春色☆こみゅにけ～しょん", ["Terios/春色☆こみゅにけ～しょん/xp3filter.tjs"]],
[1429195795, "エフォルダムソフトcrown", "夢か現かマトリョーシカ", "夢か現かマトリョーシカ", ["エフォルダムソフトcrown/夢か現かマトリョーシカ/xp3filter.tjs"]],
[1428853512, "NanaWind", "ユユカナ -under the Starlight-", "ユユカナ -under the Starlight-", ["NanaWind/ユユカナ -under the Starlight-/xp3filter.tjs"]],
[1428851115, "STELLAR", "らくてん　この世の楽園？あの世の天国！？", "らくてん　この世の楽園？あの世の天国！？", ["STELLAR/らくてん　この世の楽園？あの世の天国！？/patch.tjs"]],
[1428847107, "暁WORKS", "ハロー・レディ！ New Division", "ハロー・レディ！ New Division", ["暁WORKS/ハロー・レディ！ New Division/patch.tjs", "暁WORKS/ハロー・レディ！ New Division/xp3filter.tjs"]],
[1428737716, "ユニゾンシフト アクセント", "流星☆キセキ -Shooting probe-", "流星☆キセキ -Shooting probe-", ["ユニゾンシフト アクセント/流星☆キセキ -Shooting probe-/xp3filter.tjs"]],
[1428338616, "Marron", "ひまわりのチャペルできみと", "ひまわりのチャペルできみと", ["Marron/ひまわりのチャペルできみと/patch.tjs"]],
[1428338286, "Hybrid Balloon", "孕辱の王妃とその姫君", "孕辱の王妃とその姫君", ["Hybrid Balloon/孕辱の王妃とその姫君/xp3filter.tjs"]],
[1427975833, "feng (フォン)", "彼女のセイイキ", "彼女のセイイキ", ["feng (フォン)/彼女のセイイキ/patch.tjs"]],
[1427907358, "flap", "flap", "懐妊対戦ツンデレPonPon!! ～私が産むんだからねっ！～", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "かみたま", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "Rain memory－あまやどり－", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "カミナリっ娘注意報！～未来の予報はヨメのちハラみ！？", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "りんくす！", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "幽霊と恋したい！", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "麗しの君 ～貴女の膣内に捧ぐ～", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "flap", "flap", "麗しの君～胸躍るは俺のために～", ["flap/data.cf", "flap/patch.tjs", "flap/xp3filter.tjs"]],
[1427907358, "アンモライト", "アンモライト", "桃色恋恋（れんげ） ～姉妹とつむぐエッチな関係～", ["アンモライト/AfterInit2.tjs", "アンモライト/data.cf", "アンモライト/xp3filter.tjs"]],
[1427907358, "アンモライト", "アンモライト", "ワタシノオモイ ～愛情と淫艶と～", ["アンモライト/AfterInit2.tjs", "アンモライト/data.cf", "アンモライト/xp3filter.tjs"]],
[1427907358, "アンモライト", "アンモライト", "妻色少女 ～ふうふせいかつ、始めます～", ["アンモライト/AfterInit2.tjs", "アンモライト/data.cf", "アンモライト/xp3filter.tjs"]],
[1427907358, "アンモライト", "アンモライト", "夏色蜜汗 ～えっちな少女としたたる匂い～", ["アンモライト/AfterInit2.tjs", "アンモライト/data.cf", "アンモライト/xp3filter.tjs"]],
[1427907358, "COSMOS", "アンモライト", "ぺろぺろ☆てぃーちゃー ～ダメダメお兄ちゃんとコスプレえっち？～", ["アンモライト/AfterInit2.tjs", "アンモライト/data.cf", "アンモライト/xp3filter.tjs"]],
[1427846913, "ExTry", "ヨリドリ～魅惑の型録遊戯～", "ヨリドリ～魅惑の型録遊戯～", ["ExTry/ヨリドリ～魅惑の型録遊戯～/Kirikiri2.cfg", "ExTry/ヨリドリ～魅惑の型録遊戯～/Override2.tjs"]],
[1427845952, "Etoiles(エトワルズ)", "妹恋～しすこい～", "妹恋～しすこい～", ["Etoiles(エトワルズ)/妹恋～しすこい～/xp3filter.tjs"]],
[1427845595, "Etoiles(エトワルズ)", "ヒミツのオトメ ～ボクが女の子になった理由（わけ）～", "ヒミツのオトメ ～ボクが女の子になった理由（わけ）～", ["Etoiles(エトワルズ)/ヒミツのオトメ ～ボクが女の子になった理由（わけ）～/xp3filter.tjs"]],
[1427818803, "ES-pot（エスポット）", "マジカルチェンジゆうきくん", "マジカルチェンジゆうきくん", ["../patch/old_core_patch/Override2.tjs", "ES-pot（エスポット）/マジカルチェンジゆうきくん/patch.tjs", "ES-pot（エスポット）/マジカルチェンジゆうきくん/xp3filter.tjs"]],
[1427818803, "ES-pot（エスポット）", "桜花繚乱", "桜花繚乱", ["../patch/old_core_patch/Override2.tjs", "ES-pot（エスポット）/桜花繚乱/patch.tjs", "ES-pot（エスポット）/桜花繚乱/xp3filter.tjs"]],
[1427818803, "ES-pot（エスポット）", "淫触の辱夢", "淫触の辱夢", ["../patch/old_core_patch/Override2.tjs", "ES-pot（エスポット）/淫触の辱夢/patch.tjs", "ES-pot（エスポット）/淫触の辱夢/xp3filter.tjs"]],
[1427817552, "Eclair", "恋春アドレセンス", "恋春アドレセンス", ["Eclair/恋春アドレセンス/xp3filter.tjs"]],
[1427816198, "COSMIC CUTE", "LOVESICK PUPPIES -僕らは恋するために生まれてきた-", "LOVESICK PUPPIES -僕らは恋するために生まれてきた-", ["COSMIC CUTE/LOVESICK PUPPIES -僕らは恋するために生まれてきた-/patch.tjs", "COSMIC CUTE/LOVESICK PUPPIES -僕らは恋するために生まれてきた-/xp3filter.tjs"]],
[1427816198, "COSMIC CUTE", "グリムガーデンの少女 -witch in gleamgarden-", "グリムガーデンの少女 -witch in gleamgarden-", ["COSMIC CUTE/グリムガーデンの少女 -witch in gleamgarden-/patch.tjs", "COSMIC CUTE/グリムガーデンの少女 -witch in gleamgarden-/xp3filter.tjs"]],
[1427815806, "chuablesoft", "Sugar＋Spice2", "Sugar＋Spice2", ["chuablesoft/Sugar＋Spice2/patch.tjs"]],
[1427815357, "chuablesoft", "Sugar＋Spice！Party☆Party", "Sugar＋Spice！Party☆Party", ["chuablesoft/Sugar＋Spice！Party☆Party/patch.tjs"]],
[1427813456, "C：drive／D：drive", "理－コトワリ－ ～キミの心の零れた欠片～", "理－コトワリ－ ～キミの心の零れた欠片～", ["C：drive／D：drive/理－コトワリ－ ～キミの心の零れた欠片～/xp3filter.tjs"]],
[1424698148, "ゆずソフト", "天色＊アイルノーツ", "天色＊アイルノーツ", ["ゆずソフト/天色＊アイルノーツ/xp3filter.tjs"]],
[1424659788, "ゆずソフト", "DRACU-RIOT!", "DRACU-RIOT!", ["ゆずソフト/DRACU-RIOT!/patch.tjs", "ゆずソフト/DRACU-RIOT!/xp3filter.tjs"]],
[1424098637, "BoostFive", "SINCLIENT", "SINCLIENT", ["BoostFive/SINCLIENT/xp3filter.tjs"]],
[1424098388, "Black Rabbit", "メイド超狂イク ～服従母娘、孤島の館での淫虐調教～", "メイド超狂イク ～服従母娘、孤島の館での淫虐調教～", ["Black Rabbit/メイド超狂イク ～服従母娘、孤島の館での淫虐調教～/xp3filter.tjs"]],
[1424097949, "STELLAR", "はに×ばに", "はに×ばに", ["../patch/old_core_patch/Override2.tjs", "STELLAR/はに×ばに/patch.tjs"]],
[1424097617, "ALL-TiME", "妹が僕を狙ってる", "妹が僕を狙ってる", ["ALL-TiME/妹が僕を狙ってる/patch.tjs", "ALL-TiME/妹が僕を狙ってる/xp3filter.tjs"]],
[1424097027, "ALL-TiME", "僕だけの少女（モノ） ～狂おしいほど君が好き～", "僕だけの少女（モノ） ～狂おしいほど君が好き～", ["ALL-TiME/僕だけの少女（モノ） ～狂おしいほど君が好き～/xp3filter.tjs"]],
[1424096662, "ALL-TiME", "好きで好きでたまらない", "好きで好きでたまらない", ["ALL-TiME/好きで好きでたまらない/xp3filter.tjs"]],
[1423921379, "ALL-TiME", "ぜっちょースパイラル！！～下宿人はわがままエッチな女の子ばかり～", "ぜっちょースパイラル！！～下宿人はわがままエッチな女の子ばかり～", ["ALL-TiME/ぜっちょースパイラル！！～下宿人はわがままエッチな女の子ばかり～/patch.tjs", "ALL-TiME/ぜっちょースパイラル！！～下宿人はわがままエッチな女の子ばかり～/xp3filter.tjs"]],
[1423586998, "すたじおちゃお", "水の都の洋菓子店（パティスリー）", "水の都の洋菓子店（パティスリー）", ["すたじおちゃお/水の都の洋菓子店（パティスリー）/patch.tjs", "すたじおちゃお/水の都の洋菓子店（パティスリー）/xp3filter.tjs"]],
[1423585825, "すみっこソフト", "なつくもゆるる", "なつくもゆるる", ["すみっこソフト/なつくもゆるる/xp3filter.tjs"]],
[1423145342, "Lose", "ものべの-happy end-", "ものべの-happy end-", ["Lose/ものべの-happy end-/patch.tjs"]],
[1421573948, "蓝天使制作组", "彼岸花葬", "彼岸花葬", ["蓝天使制作组/彼岸花葬/patch.tjs", "蓝天使制作组/彼岸花葬/xp3filter.tjs"]],
[1421573766, "coryphee", "遗忘花园", "遗忘花园", ["coryphee/遗忘花园/patch.tjs", "coryphee/遗忘花园/xp3filter.tjs"]],
[1420957367, "onomatope", "俺と5人の嫁さんがラブラブなのは、未来からきた赤ちゃんのおかげに違いない！？", "俺と5人の嫁さんがラブラブなのは、未来からきた赤ちゃんのおかげに違いない！？", ["onomatope/俺と5人の嫁さんがラブラブなのは、未来からきた赤ちゃんのおかげに違いない！？/patch.tjs", "onomatope/俺と5人の嫁さんがラブラブなのは、未来からきた赤ちゃんのおかげに違いない！？/xp3filter.tjs"]],
[1420920271, "エフォルダム", "銃騎士 Cutie☆Bullet", "銃騎士 Cutie☆Bullet", ["エフォルダム/銃騎士 Cutie☆Bullet/patch.tjs", "エフォルダム/銃騎士 Cutie☆Bullet/xp3filter.tjs"]],
[1419516712, "Etoiles(エトワルズ)", "カラフル☆きゅあー", "カラフル☆きゅあー", ["Etoiles(エトワルズ)/カラフル☆きゅあー/xp3filter.tjs"]],
[1418312013, "TYPEMOON", "魔法使いの夜", "魔法使いの夜", ["TYPEMOON/魔法使いの夜/patch.tjs", "TYPEMOON/魔法使いの夜/xp3filter.tjs"]],
[1417030198, "エフォルダム", "恋騎士 Purely☆Kiss", "恋騎士 Purely☆Kiss", ["エフォルダム/恋騎士 Purely☆Kiss/AfterStartup.tjs", "エフォルダム/恋騎士 Purely☆Kiss/xp3filter.tjs"]],
[1416028141, "Nostalgic Chord", "放課後の不適格者", "放課後の不適格者", ["Nostalgic Chord/放課後の不適格者/Kirikiri2.cfg", "Nostalgic Chord/放課後の不適格者/patch.tjs", "Nostalgic Chord/放課後の不適格者/xp3filter.tjs"]],
[1414060733, "Nephrite", "夏の幼馴染と、冬のカノジョ", "夏の幼馴染と、冬のカノジョ", ["Nephrite/夏の幼馴染と、冬のカノジョ/xp3filter.tjs"]],
[1413646480, "TABLET", "茜の空に月をみる", "茜の空に月をみる", ["TABLET/茜の空に月をみる/patch.tjs"]],
[1413639306, "Yatagarasu", "ココロの住処", "ココロの住処", ["Yatagarasu/ココロの住処/patch.tjs", "Yatagarasu/ココロの住処/xp3filter.tjs"]],
[1413638115, "あるてみす", "姉婚（しすこん）", "姉婚（しすこん）", ["あるてみす/姉婚（しすこん）/xp3filter.tjs"]],
[1413637602, "インレ", "インレ", "ChuSingura 46＋1 -忠臣蔵46＋1-", ["インレ/xp3filter.tjs"]],
[1413637602, "インレ", "インレ", "ChuSingura 46＋1 -忠臣蔵46＋1- 武士の鼓動 A samurai's beat", ["インレ/xp3filter.tjs"]],
[1413637602, "インレ", "インレ", "ChuSingura 46＋1 小夜の小さな蕾。お兄ちゃん！そこは駄目！駄目！", ["インレ/xp3filter.tjs"]],
[1413637602, "インレ", "インレ", "僕はキミだけを見つめる -I gaze at only you-", ["インレ/xp3filter.tjs"]],
[1413636025, "すみっこソフト", "絶対可憐！お嬢様っ", "絶対可憐！お嬢様っ", ["すみっこソフト/絶対可憐！お嬢様っ/xp3filter.tjs"]],
[1409850035, "暁WORKS", "Bradyon Veda -ブラディオン ベーダ-", "Bradyon Veda -ブラディオン ベーダ-", ["暁WORKS/Bradyon Veda -ブラディオン ベーダ-/patch.tjs", "暁WORKS/Bradyon Veda -ブラディオン ベーダ-/xp3filter.tjs"]],
[1409765759, "WHEEL", "ぶら ぶら", "ぶら ぶら", ["WHEEL/ぶら ぶら/xp3filter.tjs"]],
[1409764532, "あっぷりけ", "アルテミスブルー", "アルテミスブルー", ["あっぷりけ/アルテミスブルー/patch.tjs", "あっぷりけ/アルテミスブルー/xp3filter.tjs"]],
[1409764325, "Shallot", "Happy Wardrobe", "Happy Wardrobe", ["Shallot/Happy Wardrobe/patch.tjs", "Shallot/Happy Wardrobe/xp3filter.tjs"]],
[1409763810, "暁WORKS-黒-", "HOTEL", "HOTEL", ["暁WORKS-黒-/HOTEL/patch.tjs", "暁WORKS-黒-/HOTEL/xp3filter.tjs"]],
[1409763597, "暁WORKS-黒-", "揺り籠より天使まで", "揺り籠より天使まで", ["暁WORKS-黒-/揺り籠より天使まで/patch.tjs", "暁WORKS-黒-/揺り籠より天使まで/xp3filter.tjs"]],
[1409762966, "暁WORKS-黒-", "イヅナ斬審剣", "イヅナ斬審剣", ["暁WORKS-黒-/イヅナ斬審剣/patch.tjs", "暁WORKS-黒-/イヅナ斬審剣/xp3filter.tjs"]],
[1409759980, "hibiki works", "LOVELY×CATION2 ラブラブバースデーコレクション vol.2 －出水和琴－", "LOVELY×CATION2 ラブラブバースデーコレクション vol.2 －出水和琴－", ["hibiki works/LOVELY×CATION2 ラブラブバースデーコレクション vol.2 －出水和琴－/patch.tjs", "hibiki works/LOVELY×CATION2 ラブラブバースデーコレクション vol.2 －出水和琴－/xp3filter.tjs"]],
[1409759980, "hibiki works", "LOVELY×CATION2 ラブラブバースデーコレクション Vol.3-成川 姫-", "LOVELY×CATION2 ラブラブバースデーコレクション Vol.3-成川 姫-", ["hibiki works/LOVELY×CATION2 ラブラブバースデーコレクション Vol.3-成川 姫-/patch.tjs", "hibiki works/LOVELY×CATION2 ラブラブバースデーコレクション Vol.3-成川 姫-/xp3filter.tjs"]],
[1409759246, "hibiki works", "LOVELY×CATION -もうずっと初恋の日々エディション-", "LOVELY×CATION -もうずっと初恋の日々エディション-", ["../patch/hibiki works/LOVELY×CATION/xp3filter.tjs", "hibiki works/LOVELY×CATION -もうずっと初恋の日々エディション-/patch.tjs"]],
[1409756669, "暁WORKS-響-", "紫電～円環の絆～", "紫電～円環の絆～", ["暁WORKS-響-/紫電～円環の絆～/patch.tjs", "暁WORKS-響-/紫電～円環の絆～/xp3filter.tjs"]],
[1409756546, "AKABEiSOFT3 あかべぇそふとすりぃ", "暁の護衛トリニティコンプリートエディション", "暁の護衛トリニティコンプリートエディション", ["../patch/AKABEiSOFT3 あかべぇそふとすりぃ/創世奇譚アエリアル/xp3filter.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/暁の護衛トリニティコンプリートエディション/patch.tjs"]],
[1409755974, "AKABEiSOFT3 あかべぇそふとすりぃ", "創世奇譚アエリアル", "創世奇譚アエリアル", ["AKABEiSOFT3 あかべぇそふとすりぃ/創世奇譚アエリアル/patch.tjs", "AKABEiSOFT3 あかべぇそふとすりぃ/創世奇譚アエリアル/xp3filter.tjs"]],
[1409754805, "暁WORKS-黒-", "ボクがワタシになった理由(ワケ)-女装計画-", "ボクがワタシになった理由(ワケ)-女装計画-", ["暁WORKS-黒-/ボクがワタシになった理由(ワケ)-女装計画-/xp3filter.tjs"]],
[1409754454, "暁WORKS", "るいは智を呼ぶファンディスク -明日のむこうに視える風-", "るいは智を呼ぶファンディスク -明日のむこうに視える風-", ["暁WORKS/るいは智を呼ぶファンディスク -明日のむこうに視える風-/xp3filter.tjs"]],
[1409750407, "暁WORKS", "るいは智を呼ぶ -フルボイスエディション-", "るいは智を呼ぶ -フルボイスエディション-", ["暁WORKS/るいは智を呼ぶ -フルボイスエディション-/xp3filter.tjs"]],
[1409748709, "暁WORKS", "‘＆’-空の向こうで咲きますように", "‘＆’-空の向こうで咲きますように", ["暁WORKS/‘＆’-空の向こうで咲きますように/xp3filter.tjs"]],
[1408942333, "Moviendo（モヴィエンド）", "処女回路（おとめかいろ）", "処女回路（おとめかいろ）", ["Moviendo（モヴィエンド）/処女回路（おとめかいろ）/patch.tjs"]],
[1407907220, "SPINDLE", "隣妻 ～昼下がりの背徳搾取～", "隣妻 ～昼下がりの背徳搾取～", ["SPINDLE/隣妻 ～昼下がりの背徳搾取～/patch.tjs"]],
[1407859958, "そらいろどっとこむ(仮)", "アノ娘の吐息2", "アノ娘の吐息2", ["そらいろどっとこむ(仮)/アノ娘の吐息2/patch.tjs"]],
[1407856614, "とらいあんぐる！", "アイドル彼女～ふたりだけの秘密レッスン～", "アイドル彼女～ふたりだけの秘密レッスン～", ["とらいあんぐる！/アイドル彼女～ふたりだけの秘密レッスン～/patch.tjs"]],
[1407855422, "ぱらいそ", "御伽話は闇の中", "御伽話は闇の中", ["ぱらいそ/御伽話は闇の中/patch.tjs"]],
[1407828331, "ぴたふぇち！", "ぴたふぇち！", "ごっくん！おさな妻～黒髪ぷに巨乳な新妻との新婚LIFE～", ["ぴたふぇち！/xp3filter.tjs"]],
[1407828331, "ぴたふぇち！", "ぴたふぇち！", "ごっくん！おにーちゃんみるく♪～ぷにぷにおっぱいな妹と～", ["ぴたふぇち！/xp3filter.tjs"]],
[1407828331, "ぴたふぇち！", "ぴたふぇち！", "ごっくん！マイダーリン～金髪ぷに巨乳な婚約者の調教DAYS～", ["ぴたふぇち！/xp3filter.tjs"]],
[1407828331, "ぴたふぇち！", "ぴたふぇち！", "幼馴染と結婚したら御付のメイドもやってきた件", ["ぴたふぇち！/xp3filter.tjs"]],
[1407690763, "ぷちぱるふぇ", "にいなちゃん Lovely Life", "にいなちゃん Lovely Life", ["ぷちぱるふぇ/にいなちゃん Lovely Life/xp3filter.tjs"]],
[1407689566, "まどそふと", "ナマイキデレーション", "ナマイキデレーション", ["まどそふと/ナマイキデレーション/xp3filter.tjs"]],
[1407685965, "地雷ソフト", "追奏のオーグメント", "追奏のオーグメント", ["地雷ソフト/追奏のオーグメント/xp3filter.tjs"]],
[1407685965, "地雷ソフト", "追奏のオーグメント", "平日のオーグメント", ["地雷ソフト/追奏のオーグメント/xp3filter.tjs"]],
[1407671571, "C：drive／D：drive", "シスターdeしぃしー", "シスターdeしぃしー", ["../patch/old_core_patch/Override2.tjs", "C：drive／D：drive/シスターdeしぃしー/patch.tjs"]],
[1407669449, "Aile（エール）", "relations sister×sister", "relations sister×sister", ["Aile（エール）/relations sister×sister/xp3filter.tjs"]],
[1407662982, "あっぷりけ", "コンチェルトノート", "コンチェルトノート", ["あっぷりけ/コンチェルトノート/patch.xp3", "あっぷりけ/コンチェルトノート/xp3filter.tjs"]],
[1407661252, "あっぷりけ", "アルテミスブルーSP", "アルテミスブルーSP", ["あっぷりけ/アルテミスブルーSP/patch.tjs", "あっぷりけ/アルテミスブルーSP/xp3filter.tjs"]],
[1407661044, "あっぷりけ", "Re：birth colony -Lost azurite-", "Re：birth colony -Lost azurite-", ["あっぷりけ/Re：birth colony -Lost azurite-/patch.tjs", "あっぷりけ/Re：birth colony -Lost azurite-/xp3filter.tjs"]],
[1407660154, "AKABEiSOFT2", "やや、置き場がない！", "やや、置き場がない！", ["AKABEiSOFT2/やや、置き場がない！/patch.tjs", "AKABEiSOFT2/やや、置き場がない！/xp3filter.tjs"]],
[1407466573, "C：drive／D：drive", "妹スタイル", "妹スタイル", ["C：drive／D：drive/妹スタイル/xp3filter.tjs"]],
[1407462805, "C：drive／D：drive", "Ｌ．Ｏ．Ｖ．Ｅ～告白～", "Ｌ．Ｏ．Ｖ．Ｅ～告白～", ["C：drive／D：drive/Ｌ．Ｏ．Ｖ．Ｅ～告白～/patch.tjs", "C：drive／D：drive/Ｌ．Ｏ．Ｖ．Ｅ～告白～/xp3filter.tjs"]],
[1407428353, "C：drive／D：drive", "なかだし孕メイド", "なかだし孕メイド", ["C：drive／D：drive/なかだし孕メイド/patch.tjs", "C：drive／D：drive/なかだし孕メイド/xp3filter.tjs"]],
[1407401768, "ALL-TiME", "令嬢サディスティック 下克上コンスピラシー", "令嬢サディスティック 下克上コンスピラシー", ["ALL-TiME/令嬢サディスティック 下克上コンスピラシー/patch.tjs"]],
[1407254624, "Le.Chocolat（ル・ショコラ）", "Swan Song", "Swan Song", ["Le.Chocolat（ル・ショコラ）/Swan Song/Override2.tjs", "Le.Chocolat（ル・ショコラ）/Swan Song/patch.tjs", "Le.Chocolat（ル・ショコラ）/Swan Song/xp3filter.tjs"]],
[1407254322, "Chien（シアン）", "委員長は承認せず！ ファンディスク", "委員長は承認せず！ ファンディスク", ["Chien（シアン）/委員長は承認せず！ ファンディスク/Override2.tjs"]],
[1407254322, "Flage", "old_core_patch", "妹の濡れた穴は俺のモノ", ["old_core_patch/Override2.tjs"]],
[1407254322, "Chien（シアン）", "old_core_patch", "委員長は承認せず！", ["old_core_patch/Override2.tjs"]],
[1407254322, "Chien（シアン）", "old_core_patch", "委員長は承認せず！ ファンディスク", ["old_core_patch/Override2.tjs"]],
[1407254322, "Grand Cru", "old_core_patch", "Reunion ～3日間だけのプチ同棲～", ["old_core_patch/Override2.tjs"]],
[1407254322, "Grand Cru", "old_core_patch", "しゅ～てぃんぐ妹スター☆ ～おにいちゃん、覚悟しててよね♪～", ["old_core_patch/Override2.tjs"]],
[1407254322, "スタジオ邪恋", "old_core_patch", "操心術＋", ["old_core_patch/Override2.tjs"]],
[1407254322, "TABLET", "old_core_patch", "きのこまち", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET MAD", "old_core_patch", "愛欲MAD催眠", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET MAD", "old_core_patch", "妹欲DEAD催眠", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET MAD", "old_core_patch", "肉欲デビル催眠", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "Myつま", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "サマー☆きゃんぷ", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "サマー☆すいむ", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "ママー☆きゃんぷ・ぷらす", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "White×Red", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "あの娘は○痴Girl", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "エロ温泉 ～新人女将の間違いだらけのおもてなし～", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "エロ温泉ソフマップ特典", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "おまかせっ！お勉強☆しすたぁず", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "お姉×ショタ", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "シコタマ学園ハレンチ女子寮", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "なぜか？！すぃ～とほ～む", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "ボクのママン捜し～ママをたずねたら…8人の巨乳妻でした～", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "ボクらのヒミツ基地大作戦 ～エスケープ ひとなつのおもいで～", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "ママー☆きゃんぷ ～ママと一緒に自然へかえろう♪～", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "やらせてっ！てぃーちゃー CHANGE", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "やらせてっ！てぃーちゃー Treasure Story", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "やらせてっ！てぃーちゃー Treasure Story アフター", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "やらせてっ！てぃーちゃー 卒業 ～YaraTea Graduation～", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "教えてっ！おねてぃー", ["old_core_patch/Override2.tjs"]],
[1407254322, "TRYSET", "old_core_patch", "新やらせてっ！てぃーちゃー", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "かんちち☆すい～と～陥没乳首の診療日誌～", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "ちちくりナース24時", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "皇女凌俗放送 ～楽園のプロパガンダ～", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "宿り蟲 -僕が触手で触手が僕で-", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "淫乳家族 ～僕と母と姉と妹と～", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "幼辱（ようじょく）～天使たちの檻～", ["old_core_patch/Override2.tjs"]],
[1407254322, "WestVision", "old_core_patch", "汚辱遊戯", ["old_core_patch/Override2.tjs"]],
[1407254322, "ユメスタ", "old_core_patch", "おねむりしすたー", ["old_core_patch/Override2.tjs"]],
[1407254322, "ユメスタ", "old_core_patch", "がんばりどーたー", ["old_core_patch/Override2.tjs"]],
[1407254322, "猿工房", "old_core_patch", "忍ココロ", ["old_core_patch/Override2.tjs"]],
[1407254322, "ユメウタリウム", "old_core_patch", "緋翠", ["old_core_patch/Override2.tjs"]],
[1407254322, "Parthenon（パルテノン）", "old_core_patch", "Chain Slave", ["old_core_patch/Override2.tjs"]],
[1407254322, "Parthenon（パルテノン）", "old_core_patch", "Cohabitation ～押しかけ女房はお姉さん！？～", ["old_core_patch/Override2.tjs"]],
[1407254322, "Parthenon（パルテノン）", "old_core_patch", "Lewdness Leccion ～淫らなメイドと孤独なご主人様～", ["old_core_patch/Override2.tjs"]],
[1407254322, "Parthenon（パルテノン）", "old_core_patch", "しすたぁ孕すめんと", ["old_core_patch/Override2.tjs"]],
[1407254322, "Parthenon（パルテノン）", "old_core_patch", "姉×弟～メイド喫茶細腕繁昌記～", ["old_core_patch/Override2.tjs"]],
[1407254322, "CrossTalk", "old_core_patch", "天使DEアクマ", ["old_core_patch/Override2.tjs"]],
[1407254322, "VENUS", "old_core_patch", "うたかたの蕾", ["old_core_patch/Override2.tjs"]],
[1407254322, "VENUS", "old_core_patch", "丧失のMarried Life", ["old_core_patch/Override2.tjs"]],
[1407254322, "VENUS", "old_core_patch", "絆されて・・・～空手娘・千鶴の情事～", ["old_core_patch/Override2.tjs"]],
[1407254322, "VENUS", "old_core_patch", "きんこむぎ!～家出中の金髪小麦肌娘", ["old_core_patch/Override2.tjs"]],
[1407254322, "PeasSoft", "つくしてあげるの！", "つくしてあげるの！", ["../patch/old_core_patch/Override2.tjs", "PeasSoft/つくしてあげるの！/patch.tjs"]],
[1406734470, "ALL-TiME", "すくみず×乙女＝恋心", "すくみず×乙女＝恋心", ["ALL-TiME/すくみず×乙女＝恋心/patch.tjs"]],
[1406657842, "softhouse-seal", "Boob Wars： Big Boobs vs Flat C", "Boob Wars： Big Boobs vs Flat C", ["softhouse-seal/Boob Wars： Big Boobs vs Flat C/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと", "ぱちぱちそふと", "おしおき生意気ギャル ～エロいオシオキをしたら自分からエッチを求めてきた～", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと", "ぱちぱちそふと", "えろ★らぼ ～実験するとどうしてもエロい結果にしかならない研究部～", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと", "ぱちぱちそふと", "妹とその友人がエロすぎて俺の股間がヤバイ", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと", "ぱちぱちそふと", "ヤンデレパコられデイズ", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと黒", "ぱちぱちそふと", "父に恋した淫乱娘「彩子」 ～お父さんは誰にも渡さない～", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと黒", "ぱちぱちそふと", "近親交際倶楽部", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと黒", "ぱちぱちそふと", "身代り淫行生活 ～親友を守るため、外道教師のいいなりになる優等生“映舞”～", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "ぱちぱちそふと黒", "ぱちぱちそふと", "放尿依存少女 優衣 ～おしっこ彼女を調教する簡単な方法～", ["ぱちぱちそふと/xp3filter.tjs"]],
[1406657842, "自宅すたじお", "ぱちぱちそふと", "リアルエロゲシチュエーション！", ["ぱちぱちそふと/xp3filter.tjs"]],
[1405230944, "地雷ソフト", "終奏のオーグメント", "終奏のオーグメント", ["地雷ソフト/終奏のオーグメント/xp3filter.tjs"]],
[1405229078, "すみっこソフト", "ああっお嬢様っ", "ああっお嬢様っ", ["すみっこソフト/ああっお嬢様っ/xp3filter.tjs"]],
[1405228501, "しとろんソフト", "初恋タイムカプセル～幼馴染とキャッキャうふふ～", "初恋タイムカプセル～幼馴染とキャッキャうふふ～", ["しとろんソフト/初恋タイムカプセル～幼馴染とキャッキャうふふ～/xp3filter.tjs"]],
[1405226848, "Pleats soft", "ここより、はるか -Surrounded sea in the world-", "ここより、はるか -Surrounded sea in the world-", ["Pleats soft/ここより、はるか -Surrounded sea in the world-/xp3filter.tjs"]],
[1405178620, "ko-eda", "ひなたのつき", "ひなたのつき", ["ko-eda/ひなたのつき/patch.tjs"]],
[1405176312, "Hearts", "メルクリア～水の都に恋の花束を～", "メルクリア～水の都に恋の花束を～", ["Hearts/メルクリア～水の都に恋の花束を～/xp3filter.tjs"]],
[1405175338, "ARTEMIS(あるてみす)", "xor_hash_rshift_3", "二刀追うものは一刀も得ず", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "田辺組", "xor_hash_rshift_3", "ゼロ○の使い魔～魔触の宴～", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "田辺組", "xor_hash_rshift_3", "おやすみレイパー2", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "俺のニオイは発情スイッチ", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "Temptation Refine", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "からふるエデュケーション", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "なるきす", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "らぶりながっこうせいかつ", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "らぶりながっこうせいかつomake", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "憧れのお姉ちゃんは調教志願者？！", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "純潔のソフィア～闇の精液を清純なるエルフの膣穴に～", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "堕としアナ", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "妃喰要塞 蜜壺の姫君", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "露出彼女", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "少女玩具に忘却の褥を～健忘陵辱～", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "Parthenon（パルテノン）", "xor_hash_rshift_3", "らぶりの夏休み～おじさんかんさつにっき～", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "ソフトさーくるクレージュ", "xor_hash_rshift_3", "ハメ撮り実況中継！兄妹初エッチ12時間", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "ソフトさーくるクレージュ", "xor_hash_rshift_3", "みずぎ姉妹 エロエロ×ツンツン×ヘンタイ！", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "ソフトさーくるクレージュ", "xor_hash_rshift_3", "DISCODE-2", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "ORC SOFT", "xor_hash_rshift_3", "愛妻日記 愛妻寝取られAVG", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "クレージュA(エース)", "xor_hash_rshift_3", "絶対服従催眠アプリ～憧れの先輩は僕の操り人形～", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405175338, "ORCSOFT／DWARFSOFT", "xor_hash_rshift_3", "愛妻日記 愛妻寝取られAVG", ["xor_hash_rshift_3/xp3filter.tjs"]],
[1405137083, "TYPEMOON", "Fate／hollow ataraxia", "Fate／hollow ataraxia", ["TYPEMOON/Fate／hollow ataraxia/config.ksc", "TYPEMOON/Fate／hollow ataraxia/Override2.tjs", "TYPEMOON/Fate／hollow ataraxia/patch.tjs", "TYPEMOON/Fate／hollow ataraxia/xp3filter.tjs"]],
[1405094744, "abelia", "マイくろ～オレガワタシデボクガアタシデ～", "マイくろ～オレガワタシデボクガアタシデ～", ["abelia/マイくろ～オレガワタシデボクガアタシデ～/xp3filter.tjs"]],
[1404920080, "ninetail", "GEARS of DRAGOON ～迷宮のウロボロス～", "GEARS of DRAGOON ～迷宮のウロボロス～", ["ninetail/GEARS of DRAGOON ～迷宮のウロボロス～/patch.tjs"]],
[1404914245, "すみっこソフト", "二代目は☆魔法少女", "二代目は☆魔法少女", ["すみっこソフト/二代目は☆魔法少女/xp3filter.tjs"]],
[1404551358, "ninetail", "SYOKUSYULIEN ～淫獄の大地～", "SYOKUSYULIEN ～淫獄の大地～", ["ninetail/SYOKUSYULIEN ～淫獄の大地～/patch.tjs", "ninetail/SYOKUSYULIEN ～淫獄の大地～/xp3filter.tjs"]],
[1404192297, "濡汁", "白濁姉妹 ～生意気なあの娘の顔にぶっかけろ！～", "白濁姉妹 ～生意気なあの娘の顔にぶっかけろ！～", ["濡汁/白濁姉妹 ～生意気なあの娘の顔にぶっかけろ！～/Kirikiri2.cfg", "濡汁/白濁姉妹 ～生意気なあの娘の顔にぶっかけろ！～/patch.tjs"]],
[1403621660, "野良ウサギ", "超コンカツ！ 5人の嫁 ～アレから三十路まで", "超コンカツ！ 5人の嫁 ～アレから三十路まで", ["野良ウサギ/超コンカツ！ 5人の嫁 ～アレから三十路まで/Kirikiri2.cfg"]],
[1403534216, "AKABEiSOFT2", "光輪の町、ラベンダーの少女", "光輪の町、ラベンダーの少女", ["AKABEiSOFT2/光輪の町、ラベンダーの少女/xp3filter.tjs"]],
[1403462676, "Lass", "11eyes－罪と罰と贖いの少女－", "11eyes－罪と罰と贖いの少女－", ["Lass/11eyes－罪と罰と贖いの少女－/Kirikiri2.cfg", "Lass/11eyes－罪と罰と贖いの少女－/patch.tjs", "Lass/11eyes－罪と罰と贖いの少女－/xp3filter.tjs"]],
[1403457557, "TYPEMOON", "Fate／stay night", "Fate／stay night", ["TYPEMOON/Fate／stay night/AfterInit2.tjs", "TYPEMOON/Fate／stay night/Override2.tjs", "TYPEMOON/Fate／stay night/patch.tjs", "TYPEMOON/Fate／stay night/xp3filter.tjs"]],
[1403369372, "softhouse-seal", "魔物っ娘ふぁんたじ～", "魔物っ娘ふぁんたじ～", ["softhouse-seal/魔物っ娘ふぁんたじ～/patch2.xp3"]],
[1403282453, "UNDEAD", "とらぶる! シスタールーム", "とらぶる! シスタールーム", ["UNDEAD/とらぶる! シスタールーム/xp3filter.tjs"]],
[1403279632, "rootnuko", "海空のフラグメンツ", "海空のフラグメンツ", ["rootnuko/海空のフラグメンツ/patch.tjs"]],
[1403193808, "ALL-TiME", "Candy Doll 軽量版", "Candy Doll 軽量版", ["ALL-TiME/Candy Doll 軽量版/patch2.xp3"]],
[1403192923, "Alcot", "FairChild -フェアチャイルド-", "FairChild -フェアチャイルド-", ["Alcot/FairChild -フェアチャイルド-/patch.tjs", "Alcot/FairChild -フェアチャイルド-/xp3filter.tjs"]],
[1402594339, "ハイクオソフト", "さくらさくら", "さくらさくら", ["ハイクオソフト/さくらさくら/patch.tjs", "ハイクオソフト/さくらさくら/update1.xp3", "ハイクオソフト/さくらさくら/xp3filter.tjs"]],
[1402246172, "Lass", "11eyes－Resona Forma－", "11eyes－Resona Forma－", ["Lass/11eyes－Resona Forma－/patch.tjs", "Lass/11eyes－Resona Forma－/xp3filter.tjs"]],
[1402242017, "FlyingShine", "夢見ヶ丘", "夢見ヶ丘", ["FlyingShine/夢見ヶ丘/messagelayer.tjs", "FlyingShine/夢見ヶ丘/patch.tjs", "FlyingShine/夢見ヶ丘/xp3filter.tjs"]],
[1401467783, "Silver Bullet", "桜吹雪 ～千年の恋をしました～", "桜吹雪 ～千年の恋をしました～", ["Silver Bullet/桜吹雪 ～千年の恋をしました～/patch.tjs"]],
[1401456552, "Alcot", "キッキングホース★ラプソディ", "キッキングホース★ラプソディ", ["Alcot/キッキングホース★ラプソディ/xp3filter.tjs"]],
[1400846886, "暁WORKS", "るいは智を呼ぶ", "るいは智を呼ぶ", ["暁WORKS/るいは智を呼ぶ/xp3filter.tjs"]],
[1400591943, "Hatena", "ヘリオトロープ－それは死に至る神の愛－", "ヘリオトロープ－それは死に至る神の愛－", ["Hatena/ヘリオトロープ－それは死に至る神の愛－/xp3filter.tjs"]],
[1400411760, "よかれとおもってやったのに", "My Sweet Home", "My Sweet Home", ["よかれとおもってやったのに/My Sweet Home/patch.tjs"]],
[1400324695, "ゆずソフト", "Ｅ×Ｅ", "Ｅ×Ｅ", ["ゆずソフト/Ｅ×Ｅ/xp3filter.tjs"]],
[1400190636, "ASa Project", "恋愛0キロメートル", "恋愛0キロメートル", ["ASa Project/恋愛0キロメートル/patch.tjs"]],
[1399893202, "Alcot", "鬼ごっこ！", "鬼ごっこ！", ["Alcot/鬼ごっこ！/xp3filter.tjs"]],
[1399893202, "Alcot", "鬼ごっこ！ ファンディスク", "鬼ごっこ！ ファンディスク", ["../patch/Alcot/鬼ごっこ！/xp3filter.tjs"]],
[1399811816, "カスガソフト", "カスガソフト", "忙しい人のためのこうまきょう", ["カスガソフト/patch.tjs", "カスガソフト/xp3filter.tjs"]],
[1399811816, "カスガソフト", "カスガソフト", "忙しい人のための萃夢想", ["カスガソフト/patch.tjs", "カスガソフト/xp3filter.tjs"]],
[1399798053, "ABHAR(アーヴァル)", "水平線まで何マイル？－Deep Blue Sky ＆ Pure White Wings－", "水平線まで何マイル？－Deep Blue Sky ＆ Pure White Wings－", ["ABHAR(アーヴァル)/水平線まで何マイル？－Deep Blue Sky ＆ Pure White Wings－/xp3filter.tjs"]],
[1399740870, "softhouse-seal", "ぜったい遵守☆子作り許可証ぱらだいす!! ～嗚呼、素晴らしき孕ま世界～", "ぜったい遵守☆子作り許可証ぱらだいす!! ～嗚呼、素晴らしき孕ま世界～", ["softhouse-seal/ぜったい遵守☆子作り許可証ぱらだいす!! ～嗚呼、素晴らしき孕ま世界～/patch.tjs"]],
[1399736385, "Q-X", "幻月のパンドオラ", "幻月のパンドオラ", ["Q-X/幻月のパンドオラ/patch.tjs", "Q-X/幻月のパンドオラ/xp3filter.tjs"]],
[1399736385, "SMILE スミレ", "夏恋ハイプレッシャー", "夏恋ハイプレッシャー", ["SMILE スミレ/夏恋ハイプレッシャー/patch.tjs"]],
[1399715900, "C：drive／D：drive", "復讐催眠～月の姫君は服従の夢をみるか？～", "復讐催眠～月の姫君は服従の夢をみるか？～", ["C：drive／D：drive/復讐催眠～月の姫君は服従の夢をみるか？～/patch.tjs", "C：drive／D：drive/復讐催眠～月の姫君は服従の夢をみるか？～/xp3filter.tjs"]],
[1399711715, "onomatope", "めちゃ婚！", "めちゃ婚！", ["onomatope/めちゃ婚！/xp3filter.tjs"]],
[1399647972, "ninetail", "VenusBlood -FRONTIER-", "VenusBlood -FRONTIER-", ["ninetail/VenusBlood -FRONTIER-/AfterInit2.tjs"]],
[1399305624, "AKABEiSOFT2", "W.L.O. 世界恋愛機構 L.L.S. -LOVE LOVE SHOW-", "W.L.O. 世界恋愛機構 L.L.S. -LOVE LOVE SHOW-", ["../patch/AKABEiSOFT3 あかべぇそふとすりぃ/創世奇譚アエリアル/xp3filter.tjs"]],
[1399291792, "CUBE", "CUBE", "your diary -ユアダイアリー-", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUBE", "CUBE", "your diary + H", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUBE", "CUBE", "恋する彼女の不器用な舞台", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUBE", "CUBE", "倉野くんちのふたご事情", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUFFS", "CUBE", "Berry's ～ベリーズ～", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUFFS", "CUBE", "CAFE SOURIRE", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "CUFFS", "CUBE", "イモウトノカタチ", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "HULOTTE（ユロット）", "CUBE", "叶とメグリとのその後がイチャらぶすぎてヤバい。", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "HULOTTE（ユロット）", "CUBE", "With Ribbon -ウィズ リボン-", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "HULOTTE（ユロット）", "CUBE", "妹のおかげでモテすぎてヤバい。", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399291792, "MintCUBE", "CUBE", "人気声優のつくりかた", ["CUBE/patch.tjs", "CUBE/xp3filter.tjs"]],
[1399219675, "ゆずソフト", "ぶらばん！", "ぶらばん！", ["ゆずソフト/ぶらばん！/xp3filter.tjs"]],
[1399208252, "Armonica", "link_plugins", "Skyprythem -スカイプリズム-", ["link_plugins/patch.tjs"]],
[1399208252, "Carol Works", "link_plugins", "えむリア！ 俺がドMになったのはどう考えてもお前らが悪い", ["link_plugins/patch.tjs"]],
[1399208252, "Carol Works", "link_plugins", "ボクの××は寮生たちの特権です！", ["link_plugins/patch.tjs"]],
[1399208252, "Carol Works", "link_plugins", "お嬢様と憐れな（こ）執事", ["link_plugins/patch.tjs"]],
[1399208252, "Concerto", "link_plugins", "子作りしようよ ソーマくん ～えっちな娘でもいいですか？～", ["link_plugins/patch.tjs"]],
[1399208252, "F&C", "link_plugins", "水月 弐～追憶～", ["link_plugins/patch.tjs"]],
[1399208252, "FOUNDATION", "link_plugins", "すたーらいと★アイドル -COLORFUL TOP STAGE！-", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "QUINTUPLE☆SPLASH", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "でりばらっ！ -deliverance of strays-", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "ゆめこい ～夢見る魔法少女と恋の呪文～", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "彼女と俺の恋愛日常（ラブリーデイ）", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "恋妹SWEET☆DAYS", ["link_plugins/patch.tjs"]],
[1399208252, "Parasol", "link_plugins", "晴のちきっと菜の花びより", ["link_plugins/patch.tjs"]],
[1399208252, "PINK CHUCHU", "link_plugins", "百五十年目の魔法使い", ["link_plugins/patch.tjs"]],
[1399208252, "RED-ZONE", "link_plugins", "おさわり痴漢電車", ["link_plugins/patch.tjs"]],
[1399208252, "RED-ZONE", "link_plugins", "ボクの貞操を奪わないでっ！！", ["link_plugins/patch.tjs"]],
[1399208252, "RED-ZONE", "link_plugins", "村祀り桃色紀行 さかざ村の淫祀り、汚された巫女姉妹", ["link_plugins/patch.tjs"]],
[1399208252, "RED-ZONE", "link_plugins", "村祀り桃色紀行　おのごろ村の淫祀り2", ["link_plugins/patch.tjs"]],
[1399208252, "rootnuko＋H", "link_plugins", "てにおはっ！2 ～ねぇ、もっとえっちなコトいっぱいしよ？～", ["link_plugins/patch.tjs"]],
[1399208252, "あかねそふと", "link_plugins", "へんこい 変恋≒黒歴史", ["link_plugins/patch.tjs"]],
[1399208252, "シャルラクプラス", "link_plugins", "万引娘桃色性裁 万引きした妹に鬼畜お仕置き！！", ["link_plugins/patch.tjs"]],
[1399208252, "シャルラクプラス", "link_plugins", "万引きした幼な妻に生ハメ中出し！！", ["link_plugins/patch.tjs"]],
[1399208252, "スペルメーション", "link_plugins", "パラメータ・リモコン", ["link_plugins/patch.tjs"]],
[1399208252, "スペルメーション", "link_plugins", "淫魔の波動", ["link_plugins/patch.tjs"]],
[1398931229, "Alcot", "Dang！ Dang！ 団地妻 -わたしだけの旦那さま☆-", "Dang！ Dang！ 団地妻 -わたしだけの旦那さま☆-", ["../patch/Alcot/Clover Day's/xp3filter.tjs"]],
[1398931229, "Alcot", "あえて無視するキミとの未来～Relay broadcast～", "あえて無視するキミとの未来～Relay broadcast～", ["../patch/Alcot/Clover Day's/xp3filter.tjs"]],
[1398931229, "Alcot", "中の人などいない！ トーキョー・ヒーロー・プロジェクト", "中の人などいない！ トーキョー・ヒーロー・プロジェクト", ["../patch/Alcot/Clover Day's/xp3filter.tjs"]],
[1398931229, "Alcot", "赤さんと吸血鬼。", "赤さんと吸血鬼。", ["../patch/Alcot/Clover Day's/xp3filter.tjs"]],
[1398791610, "ゆずソフト", "天神乱漫 LUCKY or UNLUCKY！？", "天神乱漫 LUCKY or UNLUCKY！？", ["ゆずソフト/天神乱漫 LUCKY or UNLUCKY！？/patch.tjs", "ゆずソフト/天神乱漫 LUCKY or UNLUCKY！？/xp3filter.tjs"]],
[1398444134, "Alcot", "クレナイノツキ", "クレナイノツキ", ["Alcot/クレナイノツキ/xp3filter.tjs"]],
[1398443135, "Chien（シアン）", "RGH～恋とヒーローと学園と～", "RGH～恋とヒーローと学園と～", ["Chien（シアン）/RGH～恋とヒーローと学園と～/xp3filter.tjs"]],
[1398443135, "Chien（シアン）", "よめはぴ～You make happy!～", "よめはぴ～You make happy!～", ["Chien（シアン）/よめはぴ～You make happy!～/xp3filter.tjs"]],
[1398443135, "Chien（シアン）", "らくがきオーバーハート", "らくがきオーバーハート", ["Chien（シアン）/らくがきオーバーハート/xp3filter.tjs"]],
[1398443135, "Chien（シアン）", "ヤ・ク・ソ・ク☆ラブハーレム", "ヤ・ク・ソ・ク☆ラブハーレム", ["Chien（シアン）/ヤ・ク・ソ・ク☆ラブハーレム/xp3filter.tjs"]],
[1398443135, "Chien（シアン）", "学園舞闘のフォークロア", "学園舞闘のフォークロア", ["Chien（シアン）/学園舞闘のフォークロア/xp3filter.tjs"]],
[1398443135, "STARGAZER", "未来戦姫 スレイブニル", "未来戦姫 スレイブニル", ["STARGAZER/未来戦姫 スレイブニル/xp3filter.tjs"]],
[1398390457, "Alcot", "春季限定 ポコ・ア・ポコ！", "春季限定 ポコ・ア・ポコ！", ["Alcot/春季限定 ポコ・ア・ポコ！/xp3filter.tjs"]],
[1398353760, "Alcot", "幼なじみは大統領", "幼なじみは大統領", ["Alcot/幼なじみは大統領/xp3filter.tjs"]],
[1398353760, "Alcot", "幼なじみは大統領", "幼なじみは大統領 ファンディスク", ["Alcot/幼なじみは大統領/xp3filter.tjs"]],
[1398176837, "Alcot", "リアル妹がいる大泉くんのばあい", "リアル妹がいる大泉くんのばあい", ["Alcot/リアル妹がいる大泉くんのばあい/xp3filter.tjs"]],
[1397837202, "ゆずソフト", "夏空カナタ", "夏空カナタ", ["ゆずソフト/夏空カナタ/xp3filter.tjs"]],
[1397584383, "TRUMPLE", "失われた未来を求めて", "失われた未来を求めて", ["TRUMPLE/失われた未来を求めて/patch.tjs", "TRUMPLE/失われた未来を求めて/xp3filter.tjs"]],
[1393766393, "AKABEiSOFT2", "Ｇ線上の魔王", "Ｇ線上の魔王", ["AKABEiSOFT2/Ｇ線上の魔王/patch.tjs"]],
[1393300588, "あっぷりけ", "黄昏のシンセミア", "黄昏のシンセミア", ["あっぷりけ/黄昏のシンセミア/xp3filter.tjs"]],
[1393261089, "KENZSOFT", "超★痴女メイド！", "超★痴女メイド！", ["KENZSOFT/超★痴女メイド！/patch.tjs"]]
];