// alternative for layeredwindow

with(Scripts) {._execStorage = .execStorage;}
Scripts.execStorage = function(name) {
	Scripts._execStorage(*);
	if(name == 'CustomYesNoDialog.tjs') {
		YesNoDialogWindow.updateButton = function() {
			bgLayer.opacity = 255;
			pileLayer.visible = false;
		};
	}
};

Window.registerExEvent = function() {};
Window.getNotificationNum = function() {return 0;};
Window.setMessageHook = function() {};
